// Quote data for the start page: 50 quotes checked against their sources where possible.
// Keep the six language lists aligned by index: English is the reference, the others translate the same entries.
window.QUOTES = {
  en: [
    { text: "Learning without thought is labour lost; thought without learning is perilous.", by: "Confucius, Analects 2.15" },
    { text: "What you do not wish for yourself, do not impose on others.", by: "Confucius, Analects 15.24" },
    { text: "Hatred is never appeased by hatred. It is appeased by non-hatred.", by: "Buddha, Dhammapada 5" },
    { text: "All that we are is the result of what we have thought.", by: "Buddha, Dhammapada 1" },
    { text: "It is not things that disturb us, but our judgements about things.", by: "Epictetus, Enchiridion 5" },
    { text: "You cannot step twice into the same river.", by: "Heraclitus" },
    { text: "The unexamined life is not worth living.", by: "Socrates, Plato's Apology" },
    { text: "The journey of a thousand miles begins with a single step.", by: "Laozi, Tao Te Ching 64" },
    { text: "Those who know do not speak. Those who speak do not know.", by: "Laozi, Tao Te Ching 56" },
    { text: "Know thyself.", by: "Inscription at Delphi" },
    { text: "Death is nothing to us, since when we are, death is not come, and when death is come, we are not.", by: "Epicurus, Letter to Menoeceus" },
    { text: "It is not that we have a short time to live, but that we waste a lot of it.", by: "Seneca, On the Shortness of Life" },
    { text: "Life is long if you know how to use it.", by: "Seneca, On the Shortness of Life" },
    { text: "We suffer more often in imagination than in reality.", by: "Seneca, Letters to Lucilius 13" },
    { text: "Begin at once to live, and count each separate day as a separate life.", by: "Seneca, Letters to Lucilius 101" },
    { text: "Some things are in our power, while others are not.", by: "Epictetus, Enchiridion 1" },
    { text: "Do not seek to have events happen as you wish, but wish them to happen as they do, and you will go on well.", by: "Epictetus, Enchiridion 8" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", by: "Marcus Aurelius, Meditations 10.16" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", by: "Marcus Aurelius, Meditations 5.20" },
    { text: "Very little is needed to make a happy life.", by: "Marcus Aurelius, Meditations 7.67" },
    { text: "Philosophy begins in wonder.", by: "Plato, Theaetetus 155d" },
    { text: "The only true wisdom is knowing that you know nothing.", by: "Socrates, after Plato's Apology 21d" },
    { text: "The beginning is the most important part of any work.", by: "Plato, Republic 377a" },
    { text: "We become just by doing just acts, and temperate by doing temperate acts.", by: "Aristotle, Nicomachean Ethics 2.1" },
    { text: "Man is by nature a political animal.", by: "Aristotle, Politics 1.2" },
    { text: "Dare to know! Have courage to use your own understanding.", by: "Immanuel Kant, What Is Enlightenment?" },
    { text: "What do I know?", by: "Michel de Montaigne, motto of the Essays" },
    { text: "The heart has its reasons, which reason does not know.", by: "Blaise Pascal, Pensées 277" },
    { text: "In the midst of winter, I found there was, within me, an invincible summer.", by: "Albert Camus, Return to Tipasa" },
    { text: "The way up and the way down are one and the same.", by: "Heraclitus, fragment 60" },
    { text: "A person's character is his fate.", by: "Heraclitus, fragment 119" },
    { text: "To learn and to practise what you have learned at the right times, is that not a joy?", by: "Confucius, Analects 1.1" },
    { text: "When you know a thing, to hold that you know it; when you do not know it, to allow that you do not know it: this is knowledge.", by: "Confucius, Analects 2.17" },
    { text: "To see what is right and not to do it is want of courage.", by: "Confucius, Analects 2.24" },
    { text: "The gentleman seeks harmony, not sameness.", by: "Confucius, Analects 13.23" },
    { text: "By nature, men are nearly alike; by practice, they get to be wide apart.", by: "Confucius, Analects 17.2" },
    { text: "Just as a solid rock is not shaken by the storm, so the wise are not affected by praise or blame.", by: "Buddha, Dhammapada 81" },
    { text: "Health is the greatest gift, contentment the greatest wealth.", by: "Buddha, Dhammapada 204" },
    { text: "Knowing others is intelligence; knowing yourself is true wisdom.", by: "Laozi, Tao Te Ching 33" },
    { text: "The softest thing in the world overcomes the hardest.", by: "Laozi, Tao Te Ching 43" },
    { text: "The fish trap exists because of the fish. Once you have the fish, you can forget the trap.", by: "Zhuangzi, chapter 26" },
    { text: "Appear weak when you are strong, and strong when you are weak.", by: "Sun Tzu, The Art of War" },
    { text: "In the beginner's mind there are many possibilities, but in the expert's there are few.", by: "Shunryu Suzuki, Zen Mind, Beginner's Mind" },
    { text: "You have a right to your actions, but never to their fruits.", by: "Bhagavad Gita 2.47" },
    { text: "Everything flows, nothing stands still.", by: "Heraclitus" },
    { text: "Yield and you will be preserved.", by: "Laozi, Tao Te Ching 22" },
    { text: "To thine own self be true.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "To every thing there is a season.", by: "Ecclesiastes 3:1" },
    { text: "One is one's own protector; who else could be the protector?", by: "Buddha, Dhammapada 160" },
    { text: "Do not be overcome by evil, but overcome evil with good.", by: "Romans 12:21" },
  ],
  nl: [
    { text: "Leren zonder nadenken levert niets op; nadenken zonder leren is gevaarlijk.", by: "Confucius, Analecten 2.15" },
    { text: "Wat je zelf niet wilt, doe dat ook een ander niet.", by: "Confucius, Analecten 15.24" },
    { text: "Haat wordt nooit gestild door haat; haat wordt gestild door niet-haat.", by: "Boeddha, Dhammapada 5" },
    { text: "Wat we denken, dat worden we. Alles wat we zijn, komt voort uit onze gedachten.", by: "Boeddha, Dhammapada 1" },
    { text: "Niet de dingen zelf verontrusten ons, maar onze opvattingen over de dingen.", by: "Epictetus, Handboekje 5" },
    { text: "Je kunt niet twee keer in dezelfde rivier stappen.", by: "Heraclitus" },
    { text: "Een leven zonder onderzoek is het leven niet waard.", by: "Socrates, Plato's Apologie" },
    { text: "Een reis van duizend mijl begint met één stap.", by: "Laozi, Tao Te King 64" },
    { text: "Wie weet, spreekt niet; wie spreekt, weet niet.", by: "Laozi, Tao Te King 56" },
    { text: "Ken uzelf.", by: "Inscriptie in Delphi" },
    { text: "De dood is niets voor ons; zolang wij er zijn, is de dood er niet, en wanneer de dood er is, zijn wij er niet.", by: "Epicurus, Brief aan Menoeceus" },
    { text: "Het is niet dat we weinig tijd hebben, maar dat we veel ervan verspillen.", by: "Seneca, Over de kortheid van het leven" },
    { text: "Het leven is lang als je weet hoe je het gebruikt.", by: "Seneca, Over de kortheid van het leven" },
    { text: "We lijden vaker in onze verbeelding dan in werkelijkheid.", by: "Seneca, Brieven aan Lucilius 13" },
    { text: "Begin nu meteen met leven, en tel elke dag als een apart leven.", by: "Seneca, Brieven aan Lucilius 101" },
    { text: "Sommige dingen liggen in onze macht, andere niet.", by: "Epictetus, Handboekje 1" },
    { text: "Wil niet dat dingen gebeuren zoals jij wilt, maar wil dat ze gebeuren zoals ze gebeuren, dan gaat het goed met je.", by: "Epictetus, Handboekje 8" },
    { text: "Verspil geen tijd meer met discussiëren over wat een goed mens zou moeten zijn. Wees er een.", by: "Marcus Aurelius, Overpeinzingen 10.16" },
    { text: "Het obstakel voor de actie bevordert de actie. Wat in de weg staat, wordt de weg.", by: "Marcus Aurelius, Overpeinzingen 5.20" },
    { text: "Heel weinig is nodig om een gelukkig leven te maken.", by: "Marcus Aurelius, Overpeinzingen 7.67" },
    { text: "Filosofie begint met verwondering.", by: "Plato, Theaetetus 155d" },
    { text: "De enige ware wijsheid is weten dat je niets weet.", by: "Socrates, naar Platons Apologie 21d" },
    { text: "Het begin is het belangrijkste deel van elk werk.", by: "Plato, Politeia 377a" },
    { text: "We worden rechtvaardig door rechtvaardige daden te doen, en matig door matige daden te doen.", by: "Aristoteles, Ethica Nicomachea 2.1" },
    { text: "De mens is van nature een politiek wezen.", by: "Aristoteles, Politica 1.2" },
    { text: "Durf te weten! Heb de moed om je eigen verstand te gebruiken.", by: "Immanuel Kant, Wat is Verlichting?" },
    { text: "Wat weet ik?", by: "Michel de Montaigne, motto van de Essays" },
    { text: "Het hart heeft redenen die het verstand niet kent.", by: "Blaise Pascal, Pensées 277" },
    { text: "Midden in de winter vond ik in mezelf een onoverwinnelijke zomer.", by: "Albert Camus, Terugkeer naar Tipasa" },
    { text: "De weg omhoog en de weg omlaag zijn één en dezelfde.", by: "Heraclitus, fragment 60" },
    { text: "Het karakter van een mens is zijn lot.", by: "Heraclitus, fragment 119" },
    { text: "Leren en op het juiste moment herhalen wat je geleerd hebt: is dat niet een vreugde?", by: "Confucius, Analecten 1.1" },
    { text: "Als je iets weet, dan erken je dat je het weet; als je iets niet weet, dan erken je dat je het niet weet: dat is kennis.", by: "Confucius, Analecten 2.17" },
    { text: "Zien wat juist is en het niet doen, is gebrek aan moed.", by: "Confucius, Analecten 2.24" },
    { text: "De edelmoedige zoekt harmonie, niet gelijkvormigheid.", by: "Confucius, Analecten 13.23" },
    { text: "Van nature zijn mensen bijna gelijk; door de praktijk worden ze ver uit elkaar.", by: "Confucius, Analecten 17.2" },
    { text: "Zoals een stevige rots niet wordt geschud door de storm, zo worden de wijzen niet geraakt door lof of blaam.", by: "Boeddha, Dhammapada 81" },
    { text: "Gezondheid is het grootste geschenk, tevredenheid de grootste rijkdom.", by: "Boeddha, Dhammapada 204" },
    { text: "Anderen kennen is verstand; jezelf kennen is ware wijsheid.", by: "Laozi, Tao Te King 33" },
    { text: "Het zachtste in de wereld overwint het hardste.", by: "Laozi, Tao Te King 43" },
    { text: "De vistrap bestaat vanwege de vis. Als je de vis hebt, kun je de trap vergeten.", by: "Zhuangzi, hoofdstuk 26" },
    { text: "Schijn zwak als je sterk bent, en sterk als je zwak bent.", by: "Sun Tzu, De kunst van de oorlog" },
    { text: "In de beginnersgeest zijn er veel mogelijkheden, in die van de expert zijn er weinig.", by: "Shunryu Suzuki, Zen Mind, Beginner's Mind" },
    { text: "Je hebt recht op je handelingen, maar nooit op hun vruchten.", by: "Bhagavad Gita 2.47" },
    { text: "Alles stroomt, niets blijft stil.", by: "Heraclitus" },
    { text: "Geef toe, en je zult behouden blijven.", by: "Laozi, Tao Te King 22" },
    { text: "Wees jezelf getrouw.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Voor alles is er een tijd.", by: "Prediker 3:1" },
    { text: "Ieder is zijn eigen beschermer; wie anders zou de beschermer kunnen zijn?", by: "Boeddha, Dhammapada 160" },
    { text: "Laat je niet door het kwade overwinnen, maar overwin het kwade met het goede.", by: "Romeinen 12:21" },
  ],
  de: [
    { text: "Lernen ohne Nachdenken bleibt vergeblich; Nachdenken ohne Lernen ist gefährlich.", by: "Konfuzius, Gespräche 2.15" },
    { text: "Was du nicht willst, dass man dir tut, das füg auch keinem anderen zu.", by: "Konfuzius, Gespräche 15.24" },
    { text: "Hass wird nie durch Hass gestillt; er wird durch Nicht-Hass gestillt.", by: "Buddha, Dhammapada 5" },
    { text: "Was wir denken, das werden wir. Alles, was wir sind, entspringt unseren Gedanken.", by: "Buddha, Dhammapada 1" },
    { text: "Nicht die Dinge selbst beunruhigen uns, sondern unsere Meinungen über die Dinge.", by: "Epiktet, Handbüchlein 5" },
    { text: "Man kann nicht zweimal in denselben Fluss steigen.", by: "Heraklit" },
    { text: "Ein ungeprüftes Leben ist nicht lebenswert.", by: "Sokrates, Platons Apologie" },
    { text: "Die Reise von tausend Meilen beginnt mit einem einzigen Schritt.", by: "Laozi, Daodejing 64" },
    { text: "Wer weiß, spricht nicht; wer spricht, weiß nicht.", by: "Laozi, Daodejing 56" },
    { text: "Erkenne dich selbst.", by: "Inschrift von Delphi" },
    { text: "Der Tod geht uns nichts an: Solange wir sind, ist der Tod nicht da, und wenn der Tod da ist, sind wir nicht mehr.", by: "Epikur, Brief an Menoikeus" },
    { text: "Es ist nicht so, dass wir zu wenig Zeit haben, sondern dass wir viel davon verschwenden.", by: "Seneca, Von der Kürze des Lebens" },
    { text: "Das Leben ist lang, wenn man weiß, wie man es nutzt.", by: "Seneca, Von der Kürze des Lebens" },
    { text: "Wir leiden öfter in der Vorstellung als in der Wirklichkeit.", by: "Seneca, Briefe an Lucilius 13" },
    { text: "Fang sofort an zu leben und zähle jeden einzelnen Tag als ein eigenes Leben.", by: "Seneca, Briefe an Lucilius 101" },
    { text: "Manches liegt in unserer Macht, anderes nicht.", by: "Epiktet, Handbüchlein 1" },
    { text: "Wünsche nicht, dass die Dinge so geschehen, wie du willst, sondern wolle, dass sie geschehen, wie sie geschehen, dann wird es dir gut gehen.", by: "Epiktet, Handbüchlein 8" },
    { text: "Verschwende keine Zeit mehr damit, darüber zu streiten, was ein guter Mensch sein sollte. Sei einer.", by: "Marc Aurel, Selbstbetrachtungen 10.16" },
    { text: "Das Hindernis für das Handeln fördert das Handeln. Was im Weg steht, wird zum Weg.", by: "Marc Aurel, Selbstbetrachtungen 5.20" },
    { text: "Sehr wenig braucht es, um ein glückliches Leben zu führen.", by: "Marc Aurel, Selbstbetrachtungen 7.67" },
    { text: "Die Philosophie beginnt mit dem Staunen.", by: "Platon, Theaitetos 155d" },
    { text: "Die einzig wahre Weisheit ist zu wissen, dass man nichts weiß.", by: "Sokrates, nach Platons Apologie 21d" },
    { text: "Der Anfang ist der wichtigste Teil jeder Arbeit.", by: "Platon, Politeia 377a" },
    { text: "Wir werden gerecht, indem wir gerechte Taten tun, und besonnen, indem wir besonnene Taten tun.", by: "Aristoteles, Nikomachische Ethik 2.1" },
    { text: "Der Mensch ist von Natur aus ein politisches Lebewesen.", by: "Aristoteles, Politik 1.2" },
    { text: "Wage es, zu wissen! Habe den Mut, deines eigenen Verstandes dich zu bedienen.", by: "Immanuel Kant, Was ist Aufklärung?" },
    { text: "Was weiß ich?", by: "Michel de Montaigne, Leitspruch der Essais" },
    { text: "Das Herz hat Gründe, die der Verstand nicht kennt.", by: "Blaise Pascal, Gedanken 277" },
    { text: "Mitten im Winter fand ich in mir einen unbesiegbaren Sommer.", by: "Albert Camus, Rückkehr nach Tipasa" },
    { text: "Der Weg hinauf und der Weg hinab sind ein und derselbe.", by: "Heraklit, Fragment 60" },
    { text: "Der Charakter eines Menschen ist sein Schicksal.", by: "Heraklit, Fragment 119" },
    { text: "Lernen und zur rechten Zeit das Gelernte üben: ist das nicht eine Freude?", by: "Konfuzius, Gespräche 1.1" },
    { text: "Wenn du etwas weißt, dann halte fest, dass du es weißt, und wenn du etwas nicht weißt, dann gib zu, dass du es nicht weißt: Das ist Wissen.", by: "Konfuzius, Gespräche 2.17" },
    { text: "Das Rechte zu sehen und es nicht zu tun, ist Mangel an Mut.", by: "Konfuzius, Gespräche 2.24" },
    { text: "Der edle Mensch strebt nach Harmonie, nicht nach Gleichförmigkeit.", by: "Konfuzius, Gespräche 13.23" },
    { text: "Von Natur aus sind die Menschen einander fast gleich; durch Übung entfernen sie sich weit voneinander.", by: "Konfuzius, Gespräche 17.2" },
    { text: "So wie ein fester Fels vom Sturm nicht erschüttert wird, so lassen sich die Weisen von Lob und Tadel nicht berühren.", by: "Buddha, Dhammapada 81" },
    { text: "Gesundheit ist das größte Geschenk, Zufriedenheit der größte Reichtum.", by: "Buddha, Dhammapada 204" },
    { text: "Andere zu kennen ist Verstand; sich selbst zu kennen ist wahre Weisheit.", by: "Laozi, Tao Te King 33" },
    { text: "Das Weichste der Welt überwindet das Härteste.", by: "Laozi, Tao Te King 43" },
    { text: "Die Fischreuse gibt es des Fisches wegen. Hat man den Fisch, kann man die Reuse vergessen.", by: "Zhuangzi, Kapitel 26" },
    { text: "Erscheine schwach, wenn du stark bist, und stark, wenn du schwach bist.", by: "Sunzi, Die Kunst des Krieges" },
    { text: "Im Geist des Anfängers gibt es viele Möglichkeiten, im Geist des Experten nur wenige.", by: "Shunryu Suzuki, Zen-Geist, Anfänger-Geist" },
    { text: "Du hast ein Recht auf dein Handeln, aber niemals auf dessen Früchte.", by: "Bhagavad Gita 2.47" },
    { text: "Alles fließt, nichts bleibt stehen.", by: "Heraklit" },
    { text: "Gib nach, und du wirst bewahrt bleiben.", by: "Laozi, Tao Te King 22" },
    { text: "Sei dir selbst treu.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Alles hat seine Zeit.", by: "Prediger 3:1" },
    { text: "Man ist sich selbst der Beschützer; wer sonst könnte der Beschützer sein?", by: "Buddha, Dhammapada 160" },
    { text: "Lass dich nicht vom Bösen überwinden, sondern überwinde das Böse mit dem Guten.", by: "Römer 12:21" },
  ],
  fr: [
    { text: "Apprendre sans réfléchir est vain ; réfléchir sans apprendre est dangereux.", by: "Confucius, Entretiens 2.15" },
    { text: "Ne fais pas à autrui ce que tu ne voudrais pas qu'on te fasse.", by: "Confucius, Entretiens 15.24" },
    { text: "La haine ne s'apaise jamais par la haine ; elle s'apaise par la non-haine.", by: "Bouddha, Dhammapada 5" },
    { text: "Nous sommes ce que nous pensons. Tout ce que nous sommes naît de nos pensées.", by: "Bouddha, Dhammapada 1" },
    { text: "Ce ne sont pas les choses qui nous troublent, mais les jugements que nous portons sur elles.", by: "Épictète, Manuel 5" },
    { text: "On ne se baigne pas deux fois dans le même fleuve.", by: "Héraclite" },
    { text: "Une vie sans examen ne vaut pas la peine d'être vécue.", by: "Socrate, Apologie de Platon" },
    { text: "Le voyage de mille lieues commence par un seul pas.", by: "Lao-tseu, Tao Te King 64" },
    { text: "Celui qui sait ne parle pas ; celui qui parle ne sait pas.", by: "Lao-tseu, Tao Te King 56" },
    { text: "Connais-toi toi-même.", by: "Inscription de Delphes" },
    { text: "La mort n'est rien pour nous : tant que nous sommes, la mort n'est pas là, et quand la mort est là, nous ne sommes plus.", by: "Épicure, Lettre à Ménécée" },
    { text: "Ce n'est pas que nous ayons peu de temps à vivre, c'est que nous en perdons beaucoup.", by: "Sénèque, De la brièveté de la vie" },
    { text: "La vie est longue si l'on sait en user.", by: "Sénèque, De la brièveté de la vie" },
    { text: "Nous souffrons plus souvent en imagination que dans la réalité.", by: "Sénèque, Lettres à Lucilius 13" },
    { text: "Commence dès maintenant à vivre, et compte chaque jour comme une vie à part entière.", by: "Sénèque, Lettres à Lucilius 101" },
    { text: "Certaines choses dépendent de nous, d'autres non.", by: "Épictète, Manuel 1" },
    { text: "Ne cherche pas à ce que les événements arrivent comme tu le souhaites, mais souhaite qu'ils arrivent comme ils arrivent, et tu iras bien.", by: "Épictète, Manuel 8" },
    { text: "Ne perds plus de temps à discuter de ce que doit être un homme de bien. Sois-le.", by: "Marc Aurèle, Pensées pour moi-même 10.16" },
    { text: "L'obstacle à l'action fait avancer l'action. Ce qui se dresse sur le chemin devient le chemin.", by: "Marc Aurèle, Pensées pour moi-même 5.20" },
    { text: "Très peu de chose suffit pour faire une vie heureuse.", by: "Marc Aurèle, Pensées pour moi-même 7.67" },
    { text: "La philosophie commence dans l'émerveillement.", by: "Platon, Théétète 155d" },
    { text: "La seule vraie sagesse est de savoir que l'on ne sait rien.", by: "Socrate, d'après l'Apologie de Platon 21d" },
    { text: "Le commencement est la partie la plus importante de toute œuvre.", by: "Platon, La République 377a" },
    { text: "Nous devenons justes en accomplissant des actes justes, et tempérants en accomplissant des actes tempérants.", by: "Aristote, Éthique à Nicomaque 2.1" },
    { text: "L'homme est par nature un animal politique.", by: "Aristote, Politique 1.2" },
    { text: "Ose savoir ! Aie le courage de te servir de ton propre entendement.", by: "Emmanuel Kant, Qu'est-ce que les Lumières ?" },
    { text: "Que sais-je ?", by: "Michel de Montaigne, devise des Essais" },
    { text: "Le cœur a des raisons que la raison ne connaît point.", by: "Blaise Pascal, Pensées 277" },
    { text: "Au milieu de l'hiver, j'ai découvert en moi un été invincible.", by: "Albert Camus, Retour à Tipasa" },
    { text: "Le chemin qui monte et le chemin qui descend ne font qu'un.", by: "Héraclite, fragment 60" },
    { text: "Le caractère de l'homme est son destin.", by: "Héraclite, fragment 119" },
    { text: "Apprendre et pratiquer au bon moment ce que l'on a appris, n'est-ce pas une joie ?", by: "Confucius, Entretiens 1.1" },
    { text: "Quand tu sais une chose, reconnais que tu la sais ; quand tu ne la sais pas, reconnais que tu ne la sais pas : voilà le savoir.", by: "Confucius, Entretiens 2.17" },
    { text: "Voir ce qui est juste et ne pas le faire, c'est manquer de courage.", by: "Confucius, Entretiens 2.24" },
    { text: "L'homme de bien recherche l'harmonie, non l'uniformité.", by: "Confucius, Entretiens 13.23" },
    { text: "Par nature, les hommes se ressemblent beaucoup ; par la pratique, ils s'éloignent les uns des autres.", by: "Confucius, Entretiens 17.2" },
    { text: "Comme un roc solide n'est pas ébranlé par la tempête, les sages ne sont pas touchés par la louange ou le blâme.", by: "Bouddha, Dhammapada 81" },
    { text: "La santé est le plus grand des dons, le contentement la plus grande richesse.", by: "Bouddha, Dhammapada 204" },
    { text: "Connaître les autres est intelligence ; se connaître soi-même est la vraie sagesse.", by: "Laozi, Tao Te King 33" },
    { text: "La chose la plus souple du monde triomphe de la plus dure.", by: "Laozi, Tao Te King 43" },
    { text: "La nasse existe à cause du poisson. Une fois le poisson pris, on peut oublier la nasse.", by: "Zhuangzi, chapitre 26" },
    { text: "Parais faible lorsque tu es fort, et fort lorsque tu es faible.", by: "Sun Tzu, L'Art de la guerre" },
    { text: "Dans l'esprit du débutant, il y a bien des possibilités ; dans celui de l'expert, il y en a peu.", by: "Shunryu Suzuki, Esprit zen, esprit du débutant" },
    { text: "Tu as droit à tes actes, mais jamais à leurs fruits.", by: "Bhagavad-Gita 2.47" },
    { text: "Tout coule, rien ne demeure.", by: "Héraclite" },
    { text: "Cède, et tu seras préservé.", by: "Laozi, Tao Te King 22" },
    { text: "Sois fidèle à toi-même.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Il y a un temps pour toute chose.", by: "Ecclésiaste 3:1" },
    { text: "Chacun est son propre protecteur ; qui d'autre pourrait l'être ?", by: "Bouddha, Dhammapada 160" },
    { text: "Ne te laisse pas vaincre par le mal, mais vaincs le mal par le bien.", by: "Romains 12:21" },
  ],
  es: [
    { text: "Aprender sin reflexionar es inútil; reflexionar sin aprender es peligroso.", by: "Confucio, Analectas 2.15" },
    { text: "Lo que no quieras para ti, no lo hagas a los demás.", by: "Confucio, Analectas 15.24" },
    { text: "El odio nunca se apacigua con odio; se apacigua con no-odio.", by: "Buda, Dhammapada 5" },
    { text: "Somos lo que pensamos. Todo lo que somos surge de nuestros pensamientos.", by: "Buda, Dhammapada 1" },
    { text: "No son las cosas las que nos perturban, sino las opiniones que tenemos sobre ellas.", by: "Epicteto, Enquiridión 5" },
    { text: "No puedes bañarte dos veces en el mismo río.", by: "Heráclito" },
    { text: "Una vida sin examen no merece la pena ser vivida.", by: "Sócrates, Apología de Platón" },
    { text: "El viaje de mil millas comienza con un solo paso.", by: "Laozi, Tao Te King 64" },
    { text: "El que sabe no habla; el que habla no sabe.", by: "Laozi, Tao Te King 56" },
    { text: "Conócete a ti mismo.", by: "Inscripción de Delfos" },
    { text: "La muerte no es nada para nosotros: mientras nosotros somos, la muerte no está, y cuando la muerte está, nosotros ya no somos.", by: "Epicuro, Carta a Meneceo" },
    { text: "No es que tengamos poco tiempo de vida, sino que perdemos mucho de él.", by: "Séneca, Sobre la brevedad de la vida" },
    { text: "La vida es larga si sabes usarla.", by: "Séneca, Sobre la brevedad de la vida" },
    { text: "Sufrimos más a menudo en la imaginación que en la realidad.", by: "Séneca, Cartas a Lucilio 13" },
    { text: "Empieza ya a vivir y cuenta cada día como una vida aparte.", by: "Séneca, Cartas a Lucilio 101" },
    { text: "Algunas cosas dependen de nosotros y otras no.", by: "Epicteto, Enquiridión 1" },
    { text: "No quieras que los acontecimientos sucedan como deseas, sino desea que sucedan como suceden, y tu vida irá bien.", by: "Epicteto, Enquiridión 8" },
    { text: "No pierdas más tiempo discutiendo sobre lo que debería ser un buen hombre. Sé uno.", by: "Marco Aurelio, Meditaciones 10.16" },
    { text: "El obstáculo a la acción impulsa la acción. Lo que se interpone en el camino se convierte en el camino.", by: "Marco Aurelio, Meditaciones 5.20" },
    { text: "Muy poco se necesita para hacer una vida feliz.", by: "Marco Aurelio, Meditaciones 7.67" },
    { text: "La filosofía comienza en el asombro.", by: "Platón, Teeteto 155d" },
    { text: "La única sabiduría verdadera es saber que no sabes nada.", by: "Sócrates, según la Apología de Platón 21d" },
    { text: "El principio es la parte más importante de cualquier obra.", by: "Platón, La República 377a" },
    { text: "Nos hacemos justos practicando actos justos, y templados practicando actos templados.", by: "Aristóteles, Ética a Nicómaco 2.1" },
    { text: "El ser humano es por naturaleza un animal político.", by: "Aristóteles, Política 1.2" },
    { text: "¡Atrévete a saber! Ten el valor de servirte de tu propio entendimiento.", by: "Immanuel Kant, ¿Qué es la Ilustración?" },
    { text: "¿Qué sé yo?", by: "Michel de Montaigne, lema de los Ensayos" },
    { text: "El corazón tiene razones que la razón no conoce.", by: "Blaise Pascal, Pensamientos 277" },
    { text: "En medio del invierno descubrí que dentro de mí había un verano invencible.", by: "Albert Camus, Regreso a Tipasa" },
    { text: "El camino hacia arriba y el camino hacia abajo son uno y el mismo.", by: "Heráclito, fragmento 60" },
    { text: "El carácter de una persona es su destino.", by: "Heráclito, fragmento 119" },
    { text: "Aprender y practicar a su debido tiempo lo aprendido, ¿no es una alegría?", by: "Confucio, Analectas 1.1" },
    { text: "Cuando sabes algo, reconoce que lo sabes; cuando no lo sabes, reconoce que no lo sabes: eso es el saber.", by: "Confucio, Analectas 2.17" },
    { text: "Ver lo que es justo y no hacerlo es falta de valor.", by: "Confucio, Analectas 2.24" },
    { text: "El hombre noble busca la armonía, no la uniformidad.", by: "Confucio, Analectas 13.23" },
    { text: "Por naturaleza, los hombres son casi iguales; por la práctica, se separan mucho.", by: "Confucio, Analectas 17.2" },
    { text: "Igual que una roca sólida no es sacudida por la tormenta, los sabios no se ven afectados por el elogio ni por la censura.", by: "Buda, Dhammapada 81" },
    { text: "La salud es el mayor de los dones, el contento la mayor riqueza.", by: "Buda, Dhammapada 204" },
    { text: "Conocer a los demás es inteligencia; conocerse a sí mismo es la verdadera sabiduría.", by: "Laozi, Tao Te King 33" },
    { text: "Lo más blando del mundo vence a lo más duro.", by: "Laozi, Tao Te King 43" },
    { text: "La trampa para peces existe por el pez. Una vez atrapado el pez, puedes olvidar la trampa.", by: "Zhuangzi, capítulo 26" },
    { text: "Aparenta debilidad cuando seas fuerte, y fortaleza cuando seas débil.", by: "Sun Tzu, El arte de la guerra" },
    { text: "En la mente del principiante hay muchas posibilidades; en la del experto, pocas.", by: "Shunryu Suzuki, Mente zen, mente de principiante" },
    { text: "Tienes derecho a tus acciones, pero nunca a sus frutos.", by: "Bhagavad Gita 2.47" },
    { text: "Todo fluye, nada permanece quieto.", by: "Heráclito" },
    { text: "Cede, y serás preservado.", by: "Laozi, Tao Te King 22" },
    { text: "Sé fiel a ti mismo.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Todo tiene su tiempo.", by: "Eclesiastés 3:1" },
    { text: "Cada uno es su propio protector; ¿quién más podría serlo?", by: "Buda, Dhammapada 160" },
    { text: "No te dejes vencer por el mal; vence el mal con el bien.", by: "Romanos 12:21" },
  ],
  zh: [
    { text: "学而不思则罔，思而不学则殆。", by: "孔子《论语》2.15" },
    { text: "己所不欲，勿施于人。", by: "孔子《论语》15.24" },
    { text: "恨不以恨止，唯以不恨止。", by: "佛陀《法句经》5" },
    { text: "心为法本，心尊心使。", by: "佛陀《法句经》1" },
    { text: "使人烦恼的不是事物本身，而是人对事物的看法。", by: "爱比克泰德《手册》5" },
    { text: "人不能两次踏入同一条河流。", by: "赫拉克利特" },
    { text: "未经审视的人生不值得过。", by: "苏格拉底，柏拉图《申辩篇》" },
    { text: "千里之行，始于足下。", by: "老子《道德经》64" },
    { text: "知者不言，言者不知。", by: "老子《道德经》56" },
    { text: "认识你自己。", by: "德尔斐神庙铭文" },
    { text: "死亡与我们无关：我们存在时，死亡尚未来临；死亡来临时，我们已不复存在。", by: "伊壁鸠鲁《致墨诺寇的信》" },
    { text: "我们并非时间太少，而是浪费了太多。", by: "塞涅卡《论生命的短暂》" },
    { text: "人生很长，只要懂得如何利用。", by: "塞涅卡《论生命的短暂》" },
    { text: "我们在想象中受的苦，往往多于现实。", by: "塞涅卡《致卢西利乌斯书》13" },
    { text: "立刻开始生活，把每一天当作一生来对待。", by: "塞涅卡《致卢西利乌斯书》101" },
    { text: "有些事情在我们掌控之中，有些则不然。", by: "爱比克泰德《手册》1" },
    { text: "不要希望事情按你的意愿发生，而要希望它们按其本来的样子发生，你的人生就会顺利。", by: "爱比克泰德《手册》8" },
    { text: "不要再浪费时间争论好人应该是什么样子，去做一个好人吧。", by: "马可·奥勒留《沉思录》10.16" },
    { text: "行动的障碍反而推动行动。挡在路上的东西，本身就成了道路。", by: "马可·奥勒留《沉思录》5.20" },
    { text: "要过上幸福的生活，所需甚少。", by: "马可·奥勒留《沉思录》7.67" },
    { text: "哲学始于惊奇。", by: "柏拉图《泰阿泰德篇》155d" },
    { text: "唯一真正的智慧，是知道自己一无所知。", by: "苏格拉底，源自柏拉图《申辩篇》21d" },
    { text: "开端是任何事业中最重要的部分。", by: "柏拉图《理想国》377a" },
    { text: "我们通过做正义的事情而变得正义，通过做节制的事情而变得节制。", by: "亚里士多德《尼各马可伦理学》2.1" },
    { text: "人天生是政治动物。", by: "亚里士多德《政治学》1.2" },
    { text: "要敢于求知！要有勇气运用你自己的理智。", by: "康德《什么是启蒙？》" },
    { text: "我知道什么？", by: "蒙田《随笔集》座右铭" },
    { text: "心有其理，而理性对此一无所知。", by: "帕斯卡尔《思想录》277" },
    { text: "在严冬之中，我发现自己心中有一个不可战胜的夏天。", by: "加缪《回到提帕萨》" },
    { text: "向上的路与向下的路，本是同一条。", by: "赫拉克利特，残篇60" },
    { text: "一个人的性格就是他的命运。", by: "赫拉克利特，残篇119" },
    { text: "学而时习之，不亦说乎？", by: "孔子《论语》1.1" },
    { text: "知之为知之，不知为不知，是知也。", by: "孔子《论语》2.17" },
    { text: "见义不为，无勇也。", by: "孔子《论语》2.24" },
    { text: "君子和而不同。", by: "孔子《论语》13.23" },
    { text: "性相近也，习相远也。", by: "孔子《论语》17.2" },
    { text: "如坚固的岩石不会被风暴撼动，智者也不会因赞誉或诽谤而动摇。", by: "佛陀《法句经》81" },
    { text: "健康是最大的礼物，知足是最大的财富。", by: "佛陀《法句经》204" },
    { text: "知人者智，自知者明。", by: "老子《道德经》33" },
    { text: "天下之至柔，驰骋天下之至坚。", by: "老子《道德经》43" },
    { text: "筌者所以在鱼，得鱼而忘筌。", by: "庄子《外物》，第26章" },
    { text: "强而示之以弱，弱而示之以强。", by: "孙子《孙子兵法》" },
    { text: "初学者的心中有许多可能，专家的心中却只有少数。", by: "铃木俊隆《禅者的初心》" },
    { text: "你只有行动的权利，却没有行动成果的权利。", by: "《薄伽梵歌》2.47" },
    { text: "万物流动，无物常住。", by: "赫拉克利特" },
    { text: "委曲才能保全。", by: "老子《道德经》22" },
    { text: "忠于你自己。", by: "威廉·莎士比亚《哈姆雷特》1.3" },
    { text: "凡事都有定期。", by: "《传道书》3:1" },
    { text: "人自己是自己的依靠，除了自己，还能依靠谁？", by: "佛陀《法句经》160" },
    { text: "不要被恶所胜，要以善胜恶。", by: "《罗马书》12:21" },
  ],
};
