const root = document.documentElement
const searchForm = document.getElementById('searchform')
const searchBox = document.getElementById('search')
const engineButton = document.getElementById('engine')
const clockTime = document.getElementById('time')
const clockDate = document.getElementById('date')
const modeButtons = document.querySelectorAll('[data-theme-value]')

// Quotes: English is the full pool; other languages translate the first ten entries
// and fall back to English for the rest.
// Quotes: English is the full pool; other languages translate the same entries by index.
const quotes = {
  en: [
    { text: "Learning without thought is labour lost; thought without learning is perilous.", by: "Confucius, Analects 2.15" },
    { text: "What you do not wish for yourself, do not impose on others.", by: "Confucius, Analects 15.24" },
    { text: "Hatred is never ended by hatred. It is ended by love.", by: "Buddha, Dhammapada 5" },
    { text: "We are what we think. All that we are arises with our thoughts.", by: "Buddha, Dhammapada 1" },
    { text: "It is not things that disturb us, but our judgements about things.", by: "Epictetus, Enchiridion 5" },
    { text: "You cannot step twice into the same river.", by: "Heraclitus" },
    { text: "The unexamined life is not worth living.", by: "Socrates, Plato's Apology" },
    { text: "The journey of a thousand miles begins with a single step.", by: "Laozi, Tao Te Ching 64" },
    { text: "Those who know do not speak. Those who speak do not know.", by: "Laozi, Tao Te Ching 56" },
    { text: "Know thyself.", by: "Inscription at Delphi" },
    { text: "Death is nothing to us, since when we are, death is not, and when death is, we are not.", by: "Epicurus, Letter to Menoeceus" },
    { text: "It is not that we have a short time to live, but that we waste a lot of it.", by: "Seneca, On the Shortness of Life" },
    { text: "Life is long if you know how to use it.", by: "Seneca, On the Shortness of Life" },
    { text: "While we are postponing, life speeds by.", by: "Seneca, Letters to Lucilius" },
    { text: "Begin at once to live, and count each separate day as a separate life.", by: "Seneca, Letters to Lucilius 101" },
    { text: "Every new beginning comes from some other beginning's end.", by: "Seneca, Letters to Lucilius 36" },
    { text: "We suffer more often in imagination than in reality.", by: "Seneca, Letters to Lucilius 13" },
    { text: "Sometimes even to live is an act of courage.", by: "Seneca, Letters to Lucilius 24" },
    { text: "Some things are in our control and others are not.", by: "Epictetus, Enchiridion 1" },
    { text: "Do not seek to have events happen as you wish, but wish them to happen as they do, and you will go on well.", by: "Epictetus, Enchiridion 8" },
    { text: "First say to yourself what you would be; and then do what you have to do.", by: "Epictetus, Discourses" },
    { text: "No man is free who is not master of himself.", by: "Epictetus, Discourses" },
    { text: "The best way to avenge yourself is not to be like the one who wronged you.", by: "Marcus Aurelius, Meditations 6.6" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", by: "Marcus Aurelius, Meditations 10.16" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", by: "Marcus Aurelius, Meditations 5.20" },
    { text: "Very little is needed to make a happy life.", by: "Marcus Aurelius, Meditations 7.67" },
    { text: "Look within. Within is the fountain of good, and it will ever bubble up.", by: "Marcus Aurelius, Meditations 7.59" },
    { text: "Philosophy begins in wonder.", by: "Plato, Theaetetus 155d" },
    { text: "The only true wisdom is knowing that you know nothing.", by: "Socrates, after Plato's Apology 21d" },
    { text: "The beginning is the most important part of any work.", by: "Plato, Republic 377a" },
    { text: "We become just by doing just acts, and temperate by doing temperate acts.", by: "Aristotle, Nicomachean Ethics 2.1" },
    { text: "Man is by nature a political animal.", by: "Aristotle, Politics 1.2" },
    { text: "Dare to know! Have courage to use your own understanding.", by: "Immanuel Kant, What Is Enlightenment?" },
    { text: "What do I know?", by: "Michel de Montaigne, motto of the Essays" },
    { text: "The heart has its reasons which reason knows nothing of.", by: "Blaise Pascal, Pensées 277" },
    { text: "He who has a why to live can bear almost any how.", by: "Friedrich Nietzsche, Twilight of the Idols" },
    { text: "Whoever fights monsters should see to it that in the process he does not become a monster.", by: "Friedrich Nietzsche, Beyond Good and Evil IV.146" },
    { text: "In the midst of winter, I found there was, within me, an invincible summer.", by: "Albert Camus, Return to Tipasa" },
    { text: "The way up and the way down are one and the same.", by: "Heraclitus, fragment 60" },
    { text: "A person's character is his fate.", by: "Heraclitus, fragment 119" },
    { text: "To learn and to practise what you have learned at the right times, is that not a joy?", by: "Confucius, Analects 1.1" },
    { text: "When you know a thing, to hold that you know it; when you do not know it, to allow that you do not know it: this is knowledge.", by: "Confucius, Analects 2.17" },
    { text: "If you review the old and know the new, you may be a teacher.", by: "Confucius, Analects 2.11" },
    { text: "To see what is right and not to do it is want of courage.", by: "Confucius, Analects 2.24" },
    { text: "The wise are free from doubts.", by: "Confucius, Analects 9.29" },
    { text: "The gentleman has no anxieties or fears.", by: "Confucius, Analects 12.4" },
    { text: "The gentleman seeks harmony, not sameness.", by: "Confucius, Analects 13.23" },
    { text: "Virtue is never left alone; he who practises it will have neighbours.", by: "Confucius, Analects 4.25" },
    { text: "By nature, men are nearly alike; by practice, they get to be wide apart.", by: "Confucius, Analects 17.2" },
    { text: "Sincerity is the way of heaven.", by: "Confucius, Doctrine of the Mean 20" },
    { text: "Just as a solid rock is not shaken by the storm, so the wise are not affected by praise or blame.", by: "Buddha, Dhammapada 81" },
    { text: "Better than a thousand hollow words is one word that brings peace.", by: "Buddha, Dhammapada 100" },
    { text: "Conquer anger by non-anger.", by: "Buddha, Dhammapada 223" },
    { text: "Victory breeds hatred; the defeated live in pain.", by: "Buddha, Dhammapada 201" },
    { text: "Health is the greatest gift, contentment the greatest wealth.", by: "Buddha, Dhammapada 204" },
    { text: "The mind is restless and hard to control, but it can be trained.", by: "Buddha, Dhammapada 35" },
    { text: "Do not look at the faults of others, at what they have done or left undone.", by: "Buddha, Dhammapada 50" },
    { text: "Like a flower that is beautiful but has no scent, so are fine words fruitless when they are not acted upon.", by: "Buddha, Dhammapada 51" },
    { text: "Knowing others is intelligence; knowing yourself is true wisdom.", by: "Laozi, Tao Te Ching 33" },
    { text: "He who knows he has enough is rich.", by: "Laozi, Tao Te Ching 33" },
    { text: "The softest thing in the world overcomes the hardest.", by: "Laozi, Tao Te Ching 43" },
    { text: "The wise do not hoard. The more they do for others, the more they have.", by: "Laozi, Tao Te Ching 81" },
    { text: "A good traveller has no fixed plans and is not intent on arriving.", by: "Laozi, Tao Te Ching 27" },
    { text: "The fish trap exists because of the fish. Once you have the fish, you can forget the trap.", by: "Zhuangzi, chapter 26" },
    { text: "The perfect person uses the mind like a mirror: it grasps nothing, refuses nothing.", by: "Zhuangzi, chapter 7" },
    { text: "Do nothing that is of no use.", by: "Miyamoto Musashi, Book of Five Rings" },
    { text: "Perceive that which cannot be seen with the eye.", by: "Miyamoto Musashi, Book of Five Rings" },
    { text: "Appear weak when you are strong, and strong when you are weak.", by: "Sun Tzu, The Art of War" },
    { text: "In the beginner's mind there are many possibilities, but in the expert's there are few.", by: "Shunryu Suzuki, Zen Mind, Beginner's Mind" },
    { text: "The way of the samurai is found in death.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "You have a right to your actions, but never to their fruits.", by: "Bhagavad Gita 2.47" },
    { text: "Lead me from the unreal to the real.", by: "Brihadaranyaka Upanishad 1.3.28" },
    { text: "If I am not for myself, who will be for me? And if I am only for myself, what am I?", by: "Hillel, Pirkei Avot 1:14" },
    { text: "There is nothing new under the sun.", by: "Ecclesiastes 1:9" },
    { text: "Be still, and know.", by: "Psalm 46:10" },
    { text: "Everything flows, nothing stands still.", by: "Heraclitus" },
    { text: "You yourselves must strive; the Buddhas only point the way.", by: "Buddha, Dhammapada 276" },
    { text: "One is one's own protector; who else could be the protector?", by: "Buddha, Dhammapada 160" },
    { text: "Though one conquers a thousand times a thousand men in battle, yet the greatest conqueror is he who conquers himself.", by: "Buddha, Dhammapada 103" },
    { text: "To avoid all evil, to cultivate good, and to purify one's mind: this is the teaching of the Buddhas.", by: "Buddha, Dhammapada 183" },
    { text: "Those who know it are not equal to those who love it; those who love it are not equal to those who delight in it.", by: "Confucius, Analects 6.20" },
    { text: "Who can say that the new generation will not equal the present?", by: "Confucius, Analects 9.23" },
    { text: "The highest good is like water.", by: "Laozi, Tao Te Ching 8" },
    { text: "The sea is king of the hundred valleys because it lies below them.", by: "Laozi, Tao Te Ching 66" },
    { text: "We shape clay into a pot, but its emptiness makes it useful.", by: "Laozi, Tao Te Ching 11" },
    { text: "Without going out of your door, you can know the ways of the world.", by: "Laozi, Tao Te Ching 47" },
    { text: "Education is not putting sight into blind eyes; it is the turning of the soul.", by: "Plato, Republic 518c" },
    { text: "The aim of our inquiry is not knowledge but action.", by: "Aristotle, Nicomachean Ethics 1.3" },
    { text: "Out of the crooked timber of humanity, no straight thing was ever made.", by: "Immanuel Kant, Idea for a Universal History" },
    { text: "That which does not kill us makes us stronger.", by: "Friedrich Nietzsche, Twilight of the Idols" },
    { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", by: "Blaise Pascal, Pensées 139" },
    { text: "Do not regret what you have done.", by: "Miyamoto Musashi, Book of Five Rings" },
    { text: "Every morning, consider yourself as already dead.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "A soft answer turneth away wrath.", by: "Proverbs 15:1" },
    { text: "Do not be overcome by evil, but overcome evil with good.", by: "Romans 12:21" },
    { text: "To every thing there is a season.", by: "Ecclesiastes 3:1" },
    { text: "Indeed, with hardship comes ease.", by: "Quran 94:5-6" },
    { text: "To thine own self be true.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Difficulties strengthen the mind, as labour does the body.", by: "Seneca, Letters to Lucilius" },
    { text: "Do not spoil what you have by desiring what you have not.", by: "Epicurus" },
    { text: "It is impossible to live a pleasant life without living wisely, well and justly.", by: "Epicurus, Principal Doctrines 5" },
    { text: "Of all the things which wisdom provides to make us entirely happy, much the greatest is the possession of friendship.", by: "Epicurus, Principal Doctrines 27" },
    { text: "Yield and you will be preserved.", by: "Laozi, Tao Te Ching 22" },
    { text: "Who can wait quietly while the mud settles? Who can remain still until the moment of action?", by: "Laozi, Tao Te Ching 15" },
    { text: "The victorious strategist only seeks battle after the victory has been won.", by: "Sun Tzu, The Art of War 4" },
    { text: "Much learning does not teach understanding.", by: "Heraclitus, fragment 40" },
  ],
  nl: [
    { text: "Leren zonder nadenken levert niets op; nadenken zonder leren is gevaarlijk.", by: "Confucius, Analecten 2.15" },
    { text: "Wat je zelf niet wilt, doe dat ook een ander niet.", by: "Confucius, Analecten 15.24" },
    { text: "Haat stopt nooit door haat; haat stopt door liefde.", by: "Boeddha, Dhammapada 5" },
    { text: "Wat we denken, dat worden we. Alles wat we zijn, komt voort uit onze gedachten.", by: "Boeddha, Dhammapada 1" },
    { text: "Niet de dingen zelf verontrusten ons, maar onze opvattingen over de dingen.", by: "Epictetus, Handboekje 5" },
    { text: "Je kunt niet twee keer in dezelfde rivier stappen.", by: "Heraclitus" },
    { text: "Een leven zonder onderzoek is het leven niet waard.", by: "Socrates, Plato's Apologie" },
    { text: "Een reis van duizend mijl begint met één stap.", by: "Laozi, Tao Te King 64" },
    { text: "Wie weet, spreekt niet; wie spreekt, weet niet.", by: "Laozi, Tao Te King 56" },
    { text: "Ken uzelf.", by: "Inscriptie in Delphi" },
    { text: "De dood is niets voor ons; zolang wij er zijn, is de dood er niet, en wanneer de dood er is, zijn wij er niet.", by: "Epicurus, Brief aan Menoeceus" },
    { text: "Het is niet dat we weinig tijd hebben, maar dat we veel ervan verspillen.", by: "Seneca, Over de kortheid van het leven" },
    { text: "Het leven is lang als je weet hoe je het gebruikt.", by: "Seneca, Over de kortheid van het leven" },
    { text: "Terwijl we uitstellen, vliegt het leven voorbij.", by: "Seneca, Brieven aan Lucilius" },
    { text: "Begin nu meteen met leven, en tel elke dag als een apart leven.", by: "Seneca, Brieven aan Lucilius 101" },
    { text: "Elk nieuw begin komt voort uit het einde van een ander begin.", by: "Seneca, Brieven aan Lucilius 36" },
    { text: "We lijden vaker in onze verbeelding dan in werkelijkheid.", by: "Seneca, Brieven aan Lucilius 13" },
    { text: "Soms is zelfs leven een daad van moed.", by: "Seneca, Brieven aan Lucilius 24" },
    { text: "Sommige dingen liggen in onze macht, andere niet.", by: "Epictetus, Handboekje 1" },
    { text: "Wil niet dat dingen gebeuren zoals jij wilt, maar wil dat ze gebeuren zoals ze gebeuren, dan gaat het goed met je.", by: "Epictetus, Handboekje 8" },
    { text: "Zeg eerst tegen jezelf wat je wilt zijn, en doe dan wat je moet doen.", by: "Epictetus, Discourses" },
    { text: "Niemand is vrij die niet meester is over zichzelf.", by: "Epictetus, Discourses" },
    { text: "De beste manier om je te wreken is niet te worden als degene die je onrecht heeft aangedaan.", by: "Marcus Aurelius, Overpeinzingen 6.6" },
    { text: "Verspil geen tijd meer met discussiëren over wat een goed mens zou moeten zijn. Wees er een.", by: "Marcus Aurelius, Overpeinzingen 10.16" },
    { text: "Het obstakel voor de actie bevordert de actie. Wat in de weg staat, wordt de weg.", by: "Marcus Aurelius, Overpeinzingen 5.20" },
    { text: "Heel weinig is nodig om een gelukkig leven te maken.", by: "Marcus Aurelius, Overpeinzingen 7.67" },
    { text: "Kijk naar binnen. Binnen is de bron van het goede, en die borrelt altijd op.", by: "Marcus Aurelius, Overpeinzingen 7.59" },
    { text: "Filosofie begint met verwondering.", by: "Plato, Theaetetus 155d" },
    { text: "De enige ware wijsheid is weten dat je niets weet.", by: "Socrates, naar Platons Apologie 21d" },
    { text: "Het begin is het belangrijkste deel van elk werk.", by: "Plato, Politeia 377a" },
    { text: "We worden rechtvaardig door rechtvaardige daden te doen, en matig door matige daden te doen.", by: "Aristoteles, Ethica Nicomachea 2.1" },
    { text: "De mens is van nature een politiek wezen.", by: "Aristoteles, Politica 1.2" },
    { text: "Durf te weten! Heb de moed om je eigen verstand te gebruiken.", by: "Immanuel Kant, Wat is Verlichting?" },
    { text: "Wat weet ik?", by: "Michel de Montaigne, motto van de Essays" },
    { text: "Het hart heeft redenen die het verstand niet kent.", by: "Blaise Pascal, Pensées 277" },
    { text: "Wie een waarom heeft om te leven, kan bijna elk hoe verdragen.", by: "Friedrich Nietzsche, Götzen-Dämmerung" },
    { text: "Wie monsters bestrijdt, moet oppassen dat hij er daarbij zelf geen monster van wordt.", by: "Friedrich Nietzsche, Over goed en kwaad IV.146" },
    { text: "Midden in de winter vond ik in mezelf een onoverwinnelijke zomer.", by: "Albert Camus, Terugkeer naar Tipasa" },
    { text: "De weg omhoog en de weg omlaag zijn één en dezelfde.", by: "Heraclitus, fragment 60" },
    { text: "Het karakter van een mens is zijn lot.", by: "Heraclitus, fragment 119" },
    { text: "Leren en op het juiste moment herhalen wat je geleerd hebt: is dat niet een vreugde?", by: "Confucius, Analecten 1.1" },
    { text: "Als je iets weet, dan erken je dat je het weet; als je iets niet weet, dan erken je dat je het niet weet: dat is kennis.", by: "Confucius, Analecten 2.17" },
    { text: "Als je het oude herziet en het nieuwe kent, kun je een leraar zijn.", by: "Confucius, Analecten 2.11" },
    { text: "Zien wat juist is en het niet doen, is gebrek aan moed.", by: "Confucius, Analecten 2.24" },
    { text: "De wijzen zijn vrij van twijfel.", by: "Confucius, Analecten 9.29" },
    { text: "De edelmoedige kent geen zorgen en geen angst.", by: "Confucius, Analecten 12.4" },
    { text: "De edelmoedige zoekt harmonie, niet gelijkvormigheid.", by: "Confucius, Analecten 13.23" },
    { text: "Deugd blijft nooit alleen; wie haar beoefent, krijgt buren.", by: "Confucius, Analecten 4.25" },
    { text: "Van nature zijn mensen bijna gelijk; door de praktijk worden ze ver uit elkaar.", by: "Confucius, Analecten 17.2" },
    { text: "Oprechtheid is de weg van de hemel.", by: "Confucius, Leer van het Midden 20" },
    { text: "Zoals een stevige rots niet wordt geschud door de storm, zo worden de wijzen niet geraakt door lof of blaam.", by: "Boeddha, Dhammapada 81" },
    { text: "Beter dan duizend holle woorden is één woord dat vrede brengt.", by: "Boeddha, Dhammapada 100" },
    { text: "Overwin woede met niet-woede.", by: "Boeddha, Dhammapada 223" },
    { text: "Overwinning kweekt haat; de verliezer leeft in pijn.", by: "Boeddha, Dhammapada 201" },
    { text: "Gezondheid is het grootste geschenk, tevredenheid de grootste rijkdom.", by: "Boeddha, Dhammapada 204" },
    { text: "De geest is rusteloos en moeilijk te beheersen, maar hij kan getraind worden.", by: "Boeddha, Dhammapada 35" },
    { text: "Kijk niet naar de fouten van anderen, naar wat zij gedaan of nagelaten hebben.", by: "Boeddha, Dhammapada 50" },
    { text: "Zoals een bloem die mooi is maar geen geur heeft, zo zijn mooie woorden vruchteloos als er niet naar gehandeld wordt.", by: "Boeddha, Dhammapada 51" },
    { text: "Anderen kennen is verstand; jezelf kennen is ware wijsheid.", by: "Laozi, Tao Te King 33" },
    { text: "Wie weet dat hij genoeg heeft, is rijk.", by: "Laozi, Tao Te King 33" },
    { text: "Het zachtste in de wereld overwint het hardste.", by: "Laozi, Tao Te King 43" },
    { text: "De wijze hoordt niet op. Hoe meer hij voor anderen doet, hoe meer hij heeft.", by: "Laozi, Tao Te King 81" },
    { text: "Een goede reiziger heeft geen vaste plannen en is niet uit op aankomen.", by: "Laozi, Tao Te King 27" },
    { text: "De vistrap bestaat vanwege de vis. Als je de vis hebt, kun je de trap vergeten.", by: "Zhuangzi, hoofdstuk 26" },
    { text: "De volmaakte mens gebruikt zijn geest als een spiegel: hij grijpt niets, weigert niets.", by: "Zhuangzi, hoofdstuk 7" },
    { text: "Doe niets wat nutteloos is.", by: "Miyamoto Musashi, Boek van de vijf ringen" },
    { text: "Zie wat met het oog niet te zien is.", by: "Miyamoto Musashi, Boek van de vijf ringen" },
    { text: "Schijn zwak als je sterk bent, en sterk als je zwak bent.", by: "Sun Tzu, De kunst van de oorlog" },
    { text: "In de beginnersgeest zijn er veel mogelijkheden, in die van de expert zijn er weinig.", by: "Shunryu Suzuki, Zen Mind, Beginner's Mind" },
    { text: "De weg van de samoerai ligt in de dood.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Je hebt recht op je handelingen, maar nooit op hun vruchten.", by: "Bhagavad Gita 2.47" },
    { text: "Leid mij van het onware naar het ware.", by: "Brihadaranyaka-upanishad 1.3.28" },
    { text: "Als ik niet voor mezelf ben, wie zal dan voor mij zijn? En als ik alleen voor mezelf ben, wat ben ik dan?", by: "Hillel, Pirkee Avot 1:14" },
    { text: "Er is niets nieuws onder de zon.", by: "Prediker 1:9" },
    { text: "Wees stil, en weet.", by: "Psalm 46:11" },
    { text: "Alles stroomt, niets blijft stil.", by: "Heraclitus" },
    { text: "Jullie zelf moeten je inspannen; de Boeddha's wijzen alleen de weg.", by: "Boeddha, Dhammapada 276" },
    { text: "Ieder is zijn eigen beschermer; wie anders zou de beschermer kunnen zijn?", by: "Boeddha, Dhammapada 160" },
    { text: "Wie duizend maal duizend mannen in de strijd overwint, is toch de grootste overwinnaar die zichzelf overwint.", by: "Boeddha, Dhammapada 103" },
    { text: "Alle kwaad vermijden, het goede cultiveren en de geest zuiveren: dit is de leer van de Boeddha's.", by: "Boeddha, Dhammapada 183" },
    { text: "Wie het kent, is niet gelijk aan wie ervan houdt; wie ervan houdt, is niet gelijk aan wie er plezier in heeft.", by: "Confucius, Analecten 6.20" },
    { text: "Wie kan zeggen dat de nieuwe generatie het heden niet zal evenaren?", by: "Confucius, Analecten 9.23" },
    { text: "Het hoogste goede is als water.", by: "Laozi, Tao Te King 8" },
    { text: "De zee is koning van honderd dalen, omdat ze lager ligt dan zij.", by: "Laozi, Tao Te King 66" },
    { text: "We vormen klei tot een pot, maar zijn leegte maakt hem nuttig.", by: "Laozi, Tao Te King 11" },
    { text: "Zonder je deur uit te gaan, kun je de wegen van de wereld kennen.", by: "Laozi, Tao Te King 47" },
    { text: "Onderwijs is niet het plaatsen van zicht in blinde ogen; het is het omkeren van de ziel.", by: "Plato, Politeia 518c" },
    { text: "Het doel van ons onderzoek is niet kennis, maar handelen.", by: "Aristoteles, Ethica Nicomachea 1.3" },
    { text: "Uit het kromme hout van de mensheid is nooit iets rechts gemaakt.", by: "Immanuel Kant, Idee voor een algemene geschiedenis" },
    { text: "Wat ons niet doodt, maakt ons sterker.", by: "Friedrich Nietzsche, Götzen-Dämmerung" },
    { text: "Alle problemen van de mensheid komen voort uit het onvermogen van de mens om rustig alleen in een kamer te zitten.", by: "Blaise Pascal, Pensées 139" },
    { text: "Heb geen spijt van wat je gedaan hebt.", by: "Miyamoto Musashi, Boek van de vijf ringen" },
    { text: "Beschouw jezelf elke ochtend als al dood.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Een zacht antwoord keert de toorn af.", by: "Spreuken 15:1" },
    { text: "Laat je niet door het kwade overwinnen, maar overwin het kwade met het goede.", by: "Romeinen 12:21" },
    { text: "Voor alles is er een tijd.", by: "Prediker 3:1" },
    { text: "Waarlijk, na moeilijkheid komt verlichting.", by: "Koran 94:5-6" },
    { text: "Wees jezelf getrouw.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Tegenslag versterkt de geest, zoals arbeid het lichaam.", by: "Seneca, Brieven aan Lucilius" },
    { text: "Bederf wat je hebt niet door te verlangen naar wat je niet hebt.", by: "Epicurus" },
    { text: "Het is onmogelijk om een aangenaam leven te leiden zonder wijs, goed en rechtvaardig te leven.", by: "Epicurus, Hoofdleerstellingen 5" },
    { text: "Van alles wat wijsheid biedt om ons volledig gelukkig te maken, is vriendschap verreweg het grootste.", by: "Epicurus, Hoofdleerstellingen 27" },
    { text: "Geef toe, en je zult behouden blijven.", by: "Laozi, Tao Te King 22" },
    { text: "Wie kan geduldig wachten tot het slib bezinkt? Wie kan stil blijven tot het moment van handelen?", by: "Laozi, Tao Te King 15" },
    { text: "De overwinnende strateeg zoekt pas de strijd nadat de overwinning al behaald is.", by: "Sun Tzu, De kunst van de oorlog 4" },
    { text: "Veel leren leert nog geen begrip.", by: "Heraclitus, fragment 40" },
  ],
  de: [
    { text: "Lernen ohne Nachdenken bleibt vergeblich; Nachdenken ohne Lernen ist gefährlich.", by: "Konfuzius, Gespräche 2.15" },
    { text: "Was du nicht willst, dass man dir tut, das füg auch keinem anderen zu.", by: "Konfuzius, Gespräche 15.24" },
    { text: "Hass endet nie durch Hass. Hass endet durch Liebe.", by: "Buddha, Dhammapada 5" },
    { text: "Was wir denken, das werden wir. Alles, was wir sind, entspringt unseren Gedanken.", by: "Buddha, Dhammapada 1" },
    { text: "Nicht die Dinge selbst beunruhigen uns, sondern unsere Meinungen über die Dinge.", by: "Epiktet, Handbüchlein 5" },
    { text: "Man kann nicht zweimal in denselben Fluss steigen.", by: "Heraklit" },
    { text: "Ein ungeprüftes Leben ist nicht lebenswert.", by: "Sokrates, Platons Apologie" },
    { text: "Die Reise von tausend Meilen beginnt mit einem einzigen Schritt.", by: "Laozi, Daodejing 64" },
    { text: "Wer weiß, spricht nicht; wer spricht, weiß nicht.", by: "Laozi, Daodejing 56" },
    { text: "Erkenne dich selbst.", by: "Inschrift von Delphi" },
    { text: "Der Tod geht uns nichts an: Solange wir sind, ist der Tod nicht da, und wenn der Tod da ist, sind wir nicht mehr.", by: "Epikur, Brief an Menoikeus" },
    { text: "Es ist nicht so, dass wir zu wenig Zeit haben, sondern dass wir viel davon verschwenden.", by: "Seneca, Von der Kürze des Lebens" },
    { text: "Das Leben ist lang, wenn man weiß, wie man es nutzt.", by: "Seneca, Von der Kürze des Lebens" },
    { text: "Während wir aufschieben, eilt das Leben dahin.", by: "Seneca, Briefe an Lucilius" },
    { text: "Fang sofort an zu leben und zähle jeden einzelnen Tag als ein eigenes Leben.", by: "Seneca, Briefe an Lucilius 101" },
    { text: "Jeder neue Anfang kommt aus dem Ende eines anderen Anfangs.", by: "Seneca, Briefe an Lucilius 36" },
    { text: "Wir leiden öfter in der Vorstellung als in der Wirklichkeit.", by: "Seneca, Briefe an Lucilius 13" },
    { text: "Manchmal ist schon das Leben selbst ein Akt des Mutes.", by: "Seneca, Briefe an Lucilius 24" },
    { text: "Manches liegt in unserer Macht, anderes nicht.", by: "Epiktet, Handbüchlein 1" },
    { text: "Wünsche nicht, dass die Dinge so geschehen, wie du willst, sondern wolle, dass sie geschehen, wie sie geschehen, dann wird es dir gut gehen.", by: "Epiktet, Handbüchlein 8" },
    { text: "Sag dir zuerst, was du sein willst, und tu dann, was du tun musst.", by: "Epiktet, Diatriben" },
    { text: "Frei ist nur, wer Herr seiner selbst ist.", by: "Epiktet, Diatriben" },
    { text: "Der beste Weg, sich zu rächen, ist, nicht so zu werden wie der, der dir Unrecht getan hat.", by: "Marc Aurel, Selbstbetrachtungen 6.6" },
    { text: "Verschwende keine Zeit mehr damit, darüber zu streiten, was ein guter Mensch sein sollte. Sei einer.", by: "Marc Aurel, Selbstbetrachtungen 10.16" },
    { text: "Das Hindernis für das Handeln fördert das Handeln. Was im Weg steht, wird zum Weg.", by: "Marc Aurel, Selbstbetrachtungen 5.20" },
    { text: "Sehr wenig braucht es, um ein glückliches Leben zu führen.", by: "Marc Aurel, Selbstbetrachtungen 7.67" },
    { text: "Schau nach innen. Dort ist die Quelle des Guten, und sie wird immer wieder sprudeln.", by: "Marc Aurel, Selbstbetrachtungen 7.59" },
    { text: "Die Philosophie beginnt mit dem Staunen.", by: "Platon, Theaitetos 155d" },
    { text: "Die einzig wahre Weisheit ist zu wissen, dass man nichts weiß.", by: "Sokrates, nach Platons Apologie 21d" },
    { text: "Der Anfang ist der wichtigste Teil jeder Arbeit.", by: "Platon, Politeia 377a" },
    { text: "Wir werden gerecht, indem wir gerechte Taten tun, und besonnen, indem wir besonnene Taten tun.", by: "Aristoteles, Nikomachische Ethik 2.1" },
    { text: "Der Mensch ist von Natur aus ein politisches Lebewesen.", by: "Aristoteles, Politik 1.2" },
    { text: "Wage es, zu wissen! Habe den Mut, deines eigenen Verstandes dich zu bedienen.", by: "Immanuel Kant, Was ist Aufklärung?" },
    { text: "Was weiß ich?", by: "Michel de Montaigne, Leitspruch der Essais" },
    { text: "Das Herz hat Gründe, die der Verstand nicht kennt.", by: "Blaise Pascal, Gedanken 277" },
    { text: "Wer ein Warum zum Leben hat, erträgt fast jedes Wie.", by: "Friedrich Nietzsche, Götzen-Dämmerung" },
    { text: "Wer Ungeheuer bekämpft, sollte darauf achten, dabei nicht selbst zum Ungeheuer zu werden.", by: "Friedrich Nietzsche, Jenseits von Gut und Böse IV.146" },
    { text: "Mitten im Winter fand ich in mir einen unbesiegbaren Sommer.", by: "Albert Camus, Rückkehr nach Tipasa" },
    { text: "Der Weg hinauf und der Weg hinab sind ein und derselbe.", by: "Heraklit, Fragment 60" },
    { text: "Der Charakter eines Menschen ist sein Schicksal.", by: "Heraklit, Fragment 119" },
    { text: "Lernen und zur rechten Zeit das Gelernte üben: ist das nicht eine Freude?", by: "Konfuzius, Gespräche 1.1" },
    { text: "Wenn du etwas weißt, dann halte fest, dass du es weißt, und wenn du etwas nicht weißt, dann gib zu, dass du es nicht weißt: Das ist Wissen.", by: "Konfuzius, Gespräche 2.17" },
    { text: "Wer das Alte bedenkt und das Neue erkennt, kann ein Lehrer sein.", by: "Konfuzius, Gespräche 2.11" },
    { text: "Das Rechte zu sehen und es nicht zu tun, ist Mangel an Mut.", by: "Konfuzius, Gespräche 2.24" },
    { text: "Die Weisen sind frei von Zweifeln.", by: "Konfuzius, Gespräche 9.29" },
    { text: "Der edle Mensch kennt keine Sorgen und keine Furcht.", by: "Konfuzius, Gespräche 12.4" },
    { text: "Der edle Mensch strebt nach Harmonie, nicht nach Gleichförmigkeit.", by: "Konfuzius, Gespräche 13.23" },
    { text: "Tugend bleibt nie allein; wer sie übt, findet Nachbarn.", by: "Konfuzius, Gespräche 4.25" },
    { text: "Von Natur aus sind die Menschen einander fast gleich; durch Übung entfernen sie sich weit voneinander.", by: "Konfuzius, Gespräche 17.2" },
    { text: "Aufrichtigkeit ist der Weg des Himmels.", by: "Konfuzius, Lehre der Mitte 20" },
    { text: "So wie ein fester Fels vom Sturm nicht erschüttert wird, so lassen sich die Weisen von Lob und Tadel nicht berühren.", by: "Buddha, Dhammapada 81" },
    { text: "Besser als tausend leere Worte ist ein einziges Wort, das Frieden bringt.", by: "Buddha, Dhammapada 100" },
    { text: "Besiege den Zorn durch Nicht-Zorn.", by: "Buddha, Dhammapada 223" },
    { text: "Sieg erzeugt Hass; der Besiegte lebt in Leid.", by: "Buddha, Dhammapada 201" },
    { text: "Gesundheit ist das größte Geschenk, Zufriedenheit der größte Reichtum.", by: "Buddha, Dhammapada 204" },
    { text: "Der Geist ist unruhig und schwer zu lenken, doch er lässt sich schulen.", by: "Buddha, Dhammapada 35" },
    { text: "Achte nicht auf die Fehler der anderen, auf das, was sie getan oder unterlassen haben.", by: "Buddha, Dhammapada 50" },
    { text: "Wie eine schöne Blume ohne Duft, so sind schöne Worte fruchtlos, wenn man nicht danach handelt.", by: "Buddha, Dhammapada 51" },
    { text: "Andere zu kennen ist Verstand; sich selbst zu kennen ist wahre Weisheit.", by: "Laozi, Tao Te King 33" },
    { text: "Wer weiß, dass er genug hat, ist reich.", by: "Laozi, Tao Te King 33" },
    { text: "Das Weichste der Welt überwindet das Härteste.", by: "Laozi, Tao Te King 43" },
    { text: "Der Weise hortet nicht. Je mehr er für andere tut, desto mehr hat er.", by: "Laozi, Tao Te King 81" },
    { text: "Ein guter Reisender hat keine festen Pläne und ist nicht darauf aus, anzukommen.", by: "Laozi, Tao Te King 27" },
    { text: "Die Fischreuse gibt es des Fisches wegen. Hat man den Fisch, kann man die Reuse vergessen.", by: "Zhuangzi, Kapitel 26" },
    { text: "Der vollkommene Mensch benutzt seinen Geist wie einen Spiegel: Er ergreift nichts, er weist nichts zurück.", by: "Zhuangzi, Kapitel 7" },
    { text: "Tu nichts, was nutzlos ist.", by: "Miyamoto Musashi, Das Buch der fünf Ringe" },
    { text: "Erkenne, was mit dem Auge nicht zu sehen ist.", by: "Miyamoto Musashi, Das Buch der fünf Ringe" },
    { text: "Erscheine schwach, wenn du stark bist, und stark, wenn du schwach bist.", by: "Sunzi, Die Kunst des Krieges" },
    { text: "Im Geist des Anfängers gibt es viele Möglichkeiten, im Geist des Experten nur wenige.", by: "Shunryu Suzuki, Zen-Geist, Anfänger-Geist" },
    { text: "Der Weg des Samurai findet sich im Tod.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Du hast ein Recht auf dein Handeln, aber niemals auf dessen Früchte.", by: "Bhagavad Gita 2.47" },
    { text: "Führe mich vom Unwirklichen zum Wirklichen.", by: "Brihadaranyaka-Upanishad 1.3.28" },
    { text: "Wenn ich nicht für mich selbst bin, wer ist dann für mich? Und wenn ich nur für mich selbst bin, was bin ich dann?", by: "Hillel, Pirkei Awot 1:14" },
    { text: "Es gibt nichts Neues unter der Sonne.", by: "Prediger 1:9" },
    { text: "Seid still und erkennt.", by: "Psalm 46:11" },
    { text: "Alles fließt, nichts bleibt stehen.", by: "Heraklit" },
    { text: "Ihr müsst selbst streben; die Buddhas zeigen nur den Weg.", by: "Buddha, Dhammapada 276" },
    { text: "Man ist sich selbst der Beschützer; wer sonst könnte der Beschützer sein?", by: "Buddha, Dhammapada 160" },
    { text: "Wer tausendmal tausend Männer im Kampf besiegt, ist doch der größte Sieger, der sich selbst besiegt.", by: "Buddha, Dhammapada 103" },
    { text: "Alles Böse meiden, das Gute pflegen und den Geist läutern: Das ist die Lehre der Buddhas.", by: "Buddha, Dhammapada 183" },
    { text: "Wer es kennt, steht nicht auf einer Stufe mit dem, der es liebt; wer es liebt, steht nicht auf einer Stufe mit dem, der daran Freude hat.", by: "Konfuzius, Gespräche 6.20" },
    { text: "Wer kann sagen, dass die neue Generation der heutigen nicht ebenbürtig sein wird?", by: "Konfuzius, Gespräche 9.23" },
    { text: "Das höchste Gute gleicht dem Wasser.", by: "Laozi, Tao Te King 8" },
    { text: "Das Meer ist König der hundert Täler, weil es unter ihnen liegt.", by: "Laozi, Tao Te King 66" },
    { text: "Wir formen Ton zu einem Topf, doch seine Leere macht ihn nützlich.", by: "Laozi, Tao Te King 11" },
    { text: "Ohne vor die Tür zu gehen, kannst du die Wege der Welt erkennen.", by: "Laozi, Tao Te King 47" },
    { text: "Bildung heißt nicht, Augen in Blinde zu setzen; sie ist das Hinwenden der Seele.", by: "Platon, Politeia 518c" },
    { text: "Das Ziel unserer Untersuchung ist nicht Wissen, sondern Handeln.", by: "Aristoteles, Nikomachische Ethik 1.3" },
    { text: "Aus dem krummen Holz der Menschheit wurde nie etwas Gerades gemacht.", by: "Immanuel Kant, Idee zu einer allgemeinen Geschichte" },
    { text: "Was uns nicht umbringt, macht uns stärker.", by: "Friedrich Nietzsche, Götzen-Dämmerung" },
    { text: "Alle Probleme der Menschheit rühren daher, dass der Mensch nicht ruhig in einem Zimmer allein sitzen kann.", by: "Blaise Pascal, Gedanken 139" },
    { text: "Bereue nicht, was du getan hast.", by: "Miyamoto Musashi, Das Buch der fünf Ringe" },
    { text: "Betrachte dich jeden Morgen als bereits tot.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Eine sanfte Antwort wendet den Zorn ab.", by: "Sprüche 15:1" },
    { text: "Lass dich nicht vom Bösen überwinden, sondern überwinde das Böse mit dem Guten.", by: "Römer 12:21" },
    { text: "Alles hat seine Zeit.", by: "Prediger 3:1" },
    { text: "Wahrlich, mit der Mühsal kommt Erleichterung.", by: "Koran 94:5-6" },
    { text: "Sei dir selbst treu.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Schwierigkeiten stärken den Geist, wie Arbeit den Körper.", by: "Seneca, Briefe an Lucilius" },
    { text: "Verderbe nicht, was du hast, durch das Verlangen nach dem, was du nicht hast.", by: "Epikur" },
    { text: "Ein angenehmes Leben ist unmöglich, ohne klug, gut und gerecht zu leben.", by: "Epikur, Hauptlehrsätze 5" },
    { text: "Von allem, was die Weisheit bietet, um uns vollkommen glücklich zu machen, ist die Freundschaft bei Weitem das Größte.", by: "Epikur, Hauptlehrsätze 27" },
    { text: "Gib nach, und du wirst bewahrt bleiben.", by: "Laozi, Tao Te King 22" },
    { text: "Wer kann still warten, bis sich der Schlamm setzt? Wer kann ruhig bleiben, bis der Moment des Handelns kommt?", by: "Laozi, Tao Te King 15" },
    { text: "Der siegreiche Stratege sucht die Schlacht erst, nachdem der Sieg bereits errungen ist.", by: "Sunzi, Die Kunst des Krieges 4" },
    { text: "Viel Lernen lehrt noch kein Verstehen.", by: "Heraklit, Fragment 40" },
  ],
  fr: [
    { text: "Apprendre sans réfléchir est vain ; réfléchir sans apprendre est dangereux.", by: "Confucius, Entretiens 2.15" },
    { text: "Ne fais pas à autrui ce que tu ne voudrais pas qu'on te fasse.", by: "Confucius, Entretiens 15.24" },
    { text: "La haine ne s'apaise jamais par la haine ; elle s'apaise par l'amour.", by: "Bouddha, Dhammapada 5" },
    { text: "Nous sommes ce que nous pensons. Tout ce que nous sommes naît de nos pensées.", by: "Bouddha, Dhammapada 1" },
    { text: "Ce ne sont pas les choses qui nous troublent, mais les jugements que nous portons sur elles.", by: "Épictète, Manuel 5" },
    { text: "On ne se baigne pas deux fois dans le même fleuve.", by: "Héraclite" },
    { text: "Une vie sans examen ne vaut pas la peine d'être vécue.", by: "Socrate, Apologie de Platon" },
    { text: "Le voyage de mille lieues commence par un seul pas.", by: "Lao-tseu, Tao Te King 64" },
    { text: "Celui qui sait ne parle pas ; celui qui parle ne sait pas.", by: "Lao-tseu, Tao Te King 56" },
    { text: "Connais-toi toi-même.", by: "Inscription de Delphes" },
    { text: "La mort n'est rien pour nous : tant que nous sommes, la mort n'est pas là, et quand la mort est là, nous ne sommes plus.", by: "Épicure, Lettre à Ménécée" },
    { text: "Ce n'est pas que nous ayons peu de temps à vivre, c'est que nous en perdons beaucoup.", by: "Sénèque, De la brièveté de la vie" },
    { text: "La vie est longue si l'on sait en user.", by: "Sénèque, De la brièveté de la vie" },
    { text: "Pendant que nous remettons, la vie file.", by: "Sénèque, Lettres à Lucilius" },
    { text: "Commence dès maintenant à vivre, et compte chaque jour comme une vie à part entière.", by: "Sénèque, Lettres à Lucilius 101" },
    { text: "Tout nouveau commencement vient de la fin d'un autre commencement.", by: "Sénèque, Lettres à Lucilius 36" },
    { text: "Nous souffrons plus souvent en imagination que dans la réalité.", by: "Sénèque, Lettres à Lucilius 13" },
    { text: "Parfois, même vivre est un acte de courage.", by: "Sénèque, Lettres à Lucilius 24" },
    { text: "Certaines choses dépendent de nous, d'autres non.", by: "Épictète, Manuel 1" },
    { text: "Ne cherche pas à ce que les événements arrivent comme tu le souhaites, mais souhaite qu'ils arrivent comme ils arrivent, et tu iras bien.", by: "Épictète, Manuel 8" },
    { text: "Dis-toi d'abord ce que tu veux être, puis fais ce que tu dois faire.", by: "Épictète, Entretiens" },
    { text: "Nul n'est libre s'il n'est pas maître de lui-même.", by: "Épictète, Entretiens" },
    { text: "La meilleure façon de te venger est de ne pas ressembler à celui qui t'a fait du tort.", by: "Marc Aurèle, Pensées pour moi-même 6.6" },
    { text: "Ne perds plus de temps à discuter de ce que doit être un homme de bien. Sois-le.", by: "Marc Aurèle, Pensées pour moi-même 10.16" },
    { text: "L'obstacle à l'action fait avancer l'action. Ce qui se dresse sur le chemin devient le chemin.", by: "Marc Aurèle, Pensées pour moi-même 5.20" },
    { text: "Très peu de chose suffit pour faire une vie heureuse.", by: "Marc Aurèle, Pensées pour moi-même 7.67" },
    { text: "Regarde au-dedans de toi. Là est la source du bien, et elle jaillira toujours.", by: "Marc Aurèle, Pensées pour moi-même 7.59" },
    { text: "La philosophie commence dans l'émerveillement.", by: "Platon, Théétète 155d" },
    { text: "La seule vraie sagesse est de savoir que l'on ne sait rien.", by: "Socrate, d'après l'Apologie de Platon 21d" },
    { text: "Le commencement est la partie la plus importante de toute œuvre.", by: "Platon, La République 377a" },
    { text: "Nous devenons justes en accomplissant des actes justes, et tempérants en accomplissant des actes tempérants.", by: "Aristote, Éthique à Nicomaque 2.1" },
    { text: "L'homme est par nature un animal politique.", by: "Aristote, Politique 1.2" },
    { text: "Ose savoir ! Aie le courage de te servir de ton propre entendement.", by: "Emmanuel Kant, Qu'est-ce que les Lumières ?" },
    { text: "Que sais-je ?", by: "Michel de Montaigne, devise des Essais" },
    { text: "Le cœur a des raisons que la raison ne connaît point.", by: "Blaise Pascal, Pensées 277" },
    { text: "Celui qui a un pourquoi pour vivre peut supporter presque n'importe quel comment.", by: "Friedrich Nietzsche, Crépuscule des idoles" },
    { text: "Qui combat des monstres doit veiller à ne pas devenir monstre lui-même.", by: "Friedrich Nietzsche, Par-delà bien et mal IV.146" },
    { text: "Au milieu de l'hiver, j'ai découvert en moi un été invincible.", by: "Albert Camus, Retour à Tipasa" },
    { text: "Le chemin qui monte et le chemin qui descend ne font qu'un.", by: "Héraclite, fragment 60" },
    { text: "Le caractère de l'homme est son destin.", by: "Héraclite, fragment 119" },
    { text: "Apprendre et pratiquer au bon moment ce que l'on a appris, n'est-ce pas une joie ?", by: "Confucius, Entretiens 1.1" },
    { text: "Quand tu sais une chose, reconnais que tu la sais ; quand tu ne la sais pas, reconnais que tu ne la sais pas : voilà le savoir.", by: "Confucius, Entretiens 2.17" },
    { text: "Si tu révises le passé et connais le présent, tu peux être un maître.", by: "Confucius, Entretiens 2.11" },
    { text: "Voir ce qui est juste et ne pas le faire, c'est manquer de courage.", by: "Confucius, Entretiens 2.24" },
    { text: "Les sages sont libres de doutes.", by: "Confucius, Entretiens 9.29" },
    { text: "L'homme de bien n'a ni soucis ni craintes.", by: "Confucius, Entretiens 12.4" },
    { text: "L'homme de bien recherche l'harmonie, non l'uniformité.", by: "Confucius, Entretiens 13.23" },
    { text: "La vertu ne reste jamais seule : celui qui la pratique aura des voisins.", by: "Confucius, Entretiens 4.25" },
    { text: "Par nature, les hommes se ressemblent beaucoup ; par la pratique, ils s'éloignent les uns des autres.", by: "Confucius, Entretiens 17.2" },
    { text: "La sincérité est la voie du ciel.", by: "Confucius, L'Invariable Milieu 20" },
    { text: "Comme un roc solide n'est pas ébranlé par la tempête, les sages ne sont pas touchés par la louange ou le blâme.", by: "Bouddha, Dhammapada 81" },
    { text: "Mieux vaut un seul mot qui apporte la paix que mille paroles vides.", by: "Bouddha, Dhammapada 100" },
    { text: "Vaincs la colère par la non-colère.", by: "Bouddha, Dhammapada 223" },
    { text: "La victoire engendre la haine ; le vaincu vit dans la souffrance.", by: "Bouddha, Dhammapada 201" },
    { text: "La santé est le plus grand des dons, le contentement la plus grande richesse.", by: "Bouddha, Dhammapada 204" },
    { text: "L'esprit est agité et difficile à maîtriser, mais il peut être entraîné.", by: "Bouddha, Dhammapada 35" },
    { text: "Ne cherche pas les fautes des autres, ce qu'ils ont fait ou omis de faire.", by: "Bouddha, Dhammapada 50" },
    { text: "Comme une fleur belle mais sans parfum, les belles paroles sont vaines si elles ne sont pas suivies d'actes.", by: "Bouddha, Dhammapada 51" },
    { text: "Connaître les autres est intelligence ; se connaître soi-même est la vraie sagesse.", by: "Laozi, Tao Te King 33" },
    { text: "Celui qui sait qu'il a assez est riche.", by: "Laozi, Tao Te King 33" },
    { text: "La chose la plus souple du monde triomphe de la plus dure.", by: "Laozi, Tao Te King 43" },
    { text: "Le sage ne thésaurise pas. Plus il donne aux autres, plus il possède.", by: "Laozi, Tao Te King 81" },
    { text: "Un bon voyageur n'a pas de plan fixe et ne cherche pas à arriver.", by: "Laozi, Tao Te King 27" },
    { text: "La nasse existe à cause du poisson. Une fois le poisson pris, on peut oublier la nasse.", by: "Zhuangzi, chapitre 26" },
    { text: "L'homme parfait use de son esprit comme d'un miroir : il ne retient rien, il ne refuse rien.", by: "Zhuangzi, chapitre 7" },
    { text: "Ne fais rien qui ne serve à rien.", by: "Miyamoto Musashi, Le Livre des cinq anneaux" },
    { text: "Perçois ce qui ne peut être vu par l'œil.", by: "Miyamoto Musashi, Le Livre des cinq anneaux" },
    { text: "Parais faible lorsque tu es fort, et fort lorsque tu es faible.", by: "Sun Tzu, L'Art de la guerre" },
    { text: "Dans l'esprit du débutant, il y a bien des possibilités ; dans celui de l'expert, il y en a peu.", by: "Shunryu Suzuki, Esprit zen, esprit du débutant" },
    { text: "La voie du samouraï se trouve dans la mort.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Tu as droit à tes actes, mais jamais à leurs fruits.", by: "Bhagavad-Gita 2.47" },
    { text: "Conduis-moi de l'irréel au réel.", by: "Brihadaranyaka Upanishad 1.3.28" },
    { text: "Si je ne suis pas pour moi, qui sera pour moi ? Et si je ne suis que pour moi, que suis-je ?", by: "Hillel, Pirké Avot 1:14" },
    { text: "Rien de nouveau sous le soleil.", by: "Ecclésiaste 1:9" },
    { text: "Sois tranquille, et sache.", by: "Psaume 46:11" },
    { text: "Tout coule, rien ne demeure.", by: "Héraclite" },
    { text: "Vous devez vous efforcer vous-mêmes ; les Bouddhas ne font que montrer le chemin.", by: "Bouddha, Dhammapada 276" },
    { text: "Chacun est son propre protecteur ; qui d'autre pourrait l'être ?", by: "Bouddha, Dhammapada 160" },
    { text: "Celui qui vainc mille fois mille hommes au combat est pourtant le plus grand vainqueur s'il se vainc lui-même.", by: "Bouddha, Dhammapada 103" },
    { text: "Éviter tout mal, cultiver le bien et purifier son esprit : tel est l'enseignement des Bouddhas.", by: "Bouddha, Dhammapada 183" },
    { text: "Celui qui le connaît n'égale pas celui qui l'aime ; celui qui l'aime n'égale pas celui qui y prend plaisir.", by: "Confucius, Entretiens 6.20" },
    { text: "Qui peut dire que la jeune génération n'égalera pas celle d'aujourd'hui ?", by: "Confucius, Entretiens 9.23" },
    { text: "Le bien suprême ressemble à l'eau.", by: "Laozi, Tao Te King 8" },
    { text: "La mer est le roi des cent vallées, parce qu'elle se tient plus bas qu'elles.", by: "Laozi, Tao Te King 66" },
    { text: "On façonne l'argile pour en faire un pot, mais c'est son vide qui le rend utile.", by: "Laozi, Tao Te King 11" },
    { text: "Sans sortir de ta porte, tu peux connaître les voies du monde.", by: "Laozi, Tao Te King 47" },
    { text: "L'éducation ne consiste pas à mettre la vue dans des yeux aveugles ; elle est le retournement de l'âme.", by: "Platon, La République 518c" },
    { text: "Le but de notre recherche n'est pas la connaissance, mais l'action.", by: "Aristote, Éthique à Nicomaque 1.3" },
    { text: "Du bois tordu de l'humanité, jamais rien de droit ne fut façonné.", by: "Emmanuel Kant, Idée d'une histoire universelle" },
    { text: "Ce qui ne nous tue pas nous rend plus forts.", by: "Friedrich Nietzsche, Crépuscule des idoles" },
    { text: "Tous les malheurs des hommes viennent de leur incapacité à rester tranquillement assis seuls dans une chambre.", by: "Blaise Pascal, Pensées 139" },
    { text: "Ne regrette pas ce que tu as fait.", by: "Miyamoto Musashi, Le Livre des cinq anneaux" },
    { text: "Considère-toi chaque matin comme déjà mort.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Une réponse douce apaise la colère.", by: "Proverbes 15:1" },
    { text: "Ne te laisse pas vaincre par le mal, mais vaincs le mal par le bien.", by: "Romains 12:21" },
    { text: "Il y a un temps pour toute chose.", by: "Ecclésiaste 3:1" },
    { text: "En vérité, avec la difficulté vient la facilité.", by: "Coran 94:5-6" },
    { text: "Sois fidèle à toi-même.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Les difficultés fortifient l'esprit, comme le travail fortifie le corps.", by: "Sénèque, Lettres à Lucilius" },
    { text: "Ne gâte pas ce que tu as en désirant ce que tu n'as pas.", by: "Épicure" },
    { text: "Il est impossible de mener une vie agréable sans vivre avec sagesse, honnêteté et justice.", by: "Épicure, Maximes capitales 5" },
    { text: "De tout ce que la sagesse procure pour nous rendre pleinement heureux, le plus grand de tous est la possession de l'amitié.", by: "Épicure, Maximes capitales 27" },
    { text: "Cède, et tu seras préservé.", by: "Laozi, Tao Te King 22" },
    { text: "Qui peut attendre patiemment que la boue se dépose ? Qui peut rester immobile jusqu'au moment d'agir ?", by: "Laozi, Tao Te King 15" },
    { text: "Le stratège victorieux ne cherche la bataille qu'une fois la victoire acquise.", by: "Sun Tzu, L'Art de la guerre 4" },
    { text: "Beaucoup d'étude n'apporte pas la compréhension.", by: "Héraclite, fragment 40" },
  ],
  es: [
    { text: "Aprender sin reflexionar es inútil; reflexionar sin aprender es peligroso.", by: "Confucio, Analectas 2.15" },
    { text: "Lo que no quieras para ti, no lo hagas a los demás.", by: "Confucio, Analectas 15.24" },
    { text: "El odio nunca se extingue con odio; se extingue con amor.", by: "Buda, Dhammapada 5" },
    { text: "Somos lo que pensamos. Todo lo que somos surge de nuestros pensamientos.", by: "Buda, Dhammapada 1" },
    { text: "No son las cosas las que nos perturban, sino las opiniones que tenemos sobre ellas.", by: "Epicteto, Enquiridión 5" },
    { text: "No puedes bañarte dos veces en el mismo río.", by: "Heráclito" },
    { text: "Una vida sin examen no merece la pena ser vivida.", by: "Sócrates, Apología de Platón" },
    { text: "El viaje de mil millas comienza con un solo paso.", by: "Laozi, Tao Te King 64" },
    { text: "El que sabe no habla; el que habla no sabe.", by: "Laozi, Tao Te King 56" },
    { text: "Conócete a ti mismo.", by: "Inscripción de Delfos" },
    { text: "La muerte no es nada para nosotros: mientras nosotros somos, la muerte no está, y cuando la muerte está, nosotros ya no somos.", by: "Epicuro, Carta a Meneceo" },
    { text: "No es que tengamos poco tiempo de vida, sino que perdemos mucho de él.", by: "Séneca, Sobre la brevedad de la vida" },
    { text: "La vida es larga si sabes usarla.", by: "Séneca, Sobre la brevedad de la vida" },
    { text: "Mientras postergamos, la vida pasa volando.", by: "Séneca, Cartas a Lucilio" },
    { text: "Empieza ya a vivir y cuenta cada día como una vida aparte.", by: "Séneca, Cartas a Lucilio 101" },
    { text: "Todo nuevo comienzo surge del final de otro comienzo.", by: "Séneca, Cartas a Lucilio 36" },
    { text: "Sufrimos más a menudo en la imaginación que en la realidad.", by: "Séneca, Cartas a Lucilio 13" },
    { text: "A veces, incluso vivir es un acto de valor.", by: "Séneca, Cartas a Lucilio 24" },
    { text: "Algunas cosas dependen de nosotros y otras no.", by: "Epicteto, Enquiridión 1" },
    { text: "No quieras que los acontecimientos sucedan como deseas, sino desea que sucedan como suceden, y tu vida irá bien.", by: "Epicteto, Enquiridión 8" },
    { text: "Dite primero lo que quieres ser, y luego haz lo que tienes que hacer.", by: "Epicteto, Disertaciones" },
    { text: "No es libre quien no es dueño de sí mismo.", by: "Epicteto, Disertaciones" },
    { text: "La mejor manera de vengarte es no parecerte a quien te hizo daño.", by: "Marco Aurelio, Meditaciones 6.6" },
    { text: "No pierdas más tiempo discutiendo sobre lo que debería ser un buen hombre. Sé uno.", by: "Marco Aurelio, Meditaciones 10.16" },
    { text: "El obstáculo a la acción impulsa la acción. Lo que se interpone en el camino se convierte en el camino.", by: "Marco Aurelio, Meditaciones 5.20" },
    { text: "Muy poco se necesita para hacer una vida feliz.", by: "Marco Aurelio, Meditaciones 7.67" },
    { text: "Mira hacia dentro. Dentro está la fuente del bien, que siempre volverá a brotar.", by: "Marco Aurelio, Meditaciones 7.59" },
    { text: "La filosofía comienza en el asombro.", by: "Platón, Teeteto 155d" },
    { text: "La única sabiduría verdadera es saber que no sabes nada.", by: "Sócrates, según la Apología de Platón 21d" },
    { text: "El principio es la parte más importante de cualquier obra.", by: "Platón, La República 377a" },
    { text: "Nos hacemos justos practicando actos justos, y templados practicando actos templados.", by: "Aristóteles, Ética a Nicómaco 2.1" },
    { text: "El ser humano es por naturaleza un animal político.", by: "Aristóteles, Política 1.2" },
    { text: "¡Atrévete a saber! Ten el valor de servirte de tu propio entendimiento.", by: "Immanuel Kant, ¿Qué es la Ilustración?" },
    { text: "¿Qué sé yo?", by: "Michel de Montaigne, lema de los Ensayos" },
    { text: "El corazón tiene razones que la razón no conoce.", by: "Blaise Pascal, Pensamientos 277" },
    { text: "Quien tiene un porqué para vivir, soporta casi cualquier cómo.", by: "Friedrich Nietzsche, El crepúsculo de los ídolos" },
    { text: "Quien lucha contra monstruos debe cuidar de no convertirse él mismo en un monstruo.", by: "Friedrich Nietzsche, Más allá del bien y del mal IV.146" },
    { text: "En medio del invierno descubrí que dentro de mí había un verano invencible.", by: "Albert Camus, Regreso a Tipasa" },
    { text: "El camino hacia arriba y el camino hacia abajo son uno y el mismo.", by: "Heráclito, fragmento 60" },
    { text: "El carácter de una persona es su destino.", by: "Heráclito, fragmento 119" },
    { text: "Aprender y practicar a su debido tiempo lo aprendido, ¿no es una alegría?", by: "Confucio, Analectas 1.1" },
    { text: "Cuando sabes algo, reconoce que lo sabes; cuando no lo sabes, reconoce que no lo sabes: eso es el saber.", by: "Confucio, Analectas 2.17" },
    { text: "Si repasas lo antiguo y conoces lo nuevo, puedes ser maestro.", by: "Confucio, Analectas 2.11" },
    { text: "Ver lo que es justo y no hacerlo es falta de valor.", by: "Confucio, Analectas 2.24" },
    { text: "Los sabios están libres de dudas.", by: "Confucio, Analectas 9.29" },
    { text: "El hombre noble no tiene inquietudes ni temores.", by: "Confucio, Analectas 12.4" },
    { text: "El hombre noble busca la armonía, no la uniformidad.", by: "Confucio, Analectas 13.23" },
    { text: "La virtud nunca está sola: quien la practica tendrá vecinos.", by: "Confucio, Analectas 4.25" },
    { text: "Por naturaleza, los hombres son casi iguales; por la práctica, se separan mucho.", by: "Confucio, Analectas 17.2" },
    { text: "La sinceridad es el camino del cielo.", by: "Confucio, Doctrina del justo medio 20" },
    { text: "Igual que una roca sólida no es sacudida por la tormenta, los sabios no se ven afectados por el elogio ni por la censura.", by: "Buda, Dhammapada 81" },
    { text: "Mejor que mil palabras vacías es una sola palabra que trae paz.", by: "Buda, Dhammapada 100" },
    { text: "Vence la ira con la no-ira.", by: "Buda, Dhammapada 223" },
    { text: "La victoria engendra odio; el vencido vive en el dolor.", by: "Buda, Dhammapada 201" },
    { text: "La salud es el mayor de los dones, el contento la mayor riqueza.", by: "Buda, Dhammapada 204" },
    { text: "La mente es inquieta y difícil de dominar, pero puede entrenarse.", by: "Buda, Dhammapada 35" },
    { text: "No mires las faltas de los demás, lo que han hecho o dejado de hacer.", by: "Buda, Dhammapada 50" },
    { text: "Como una flor hermosa pero sin aroma, las palabras bellas son estériles si no se llevan a la práctica.", by: "Buda, Dhammapada 51" },
    { text: "Conocer a los demás es inteligencia; conocerse a sí mismo es la verdadera sabiduría.", by: "Laozi, Tao Te King 33" },
    { text: "Quien sabe que tiene suficiente es rico.", by: "Laozi, Tao Te King 33" },
    { text: "Lo más blando del mundo vence a lo más duro.", by: "Laozi, Tao Te King 43" },
    { text: "El sabio no acumula. Cuanto más hace por los demás, más tiene.", by: "Laozi, Tao Te King 81" },
    { text: "El buen viajero no tiene planes fijos ni se empeña en llegar.", by: "Laozi, Tao Te King 27" },
    { text: "La trampa para peces existe por el pez. Una vez atrapado el pez, puedes olvidar la trampa.", by: "Zhuangzi, capítulo 26" },
    { text: "La persona perfecta usa la mente como un espejo: no retiene nada, no rechaza nada.", by: "Zhuangzi, capítulo 7" },
    { text: "No hagas nada que no sirva para nada.", by: "Miyamoto Musashi, El libro de los cinco anillos" },
    { text: "Percibe lo que no puede verse con los ojos.", by: "Miyamoto Musashi, El libro de los cinco anillos" },
    { text: "Aparenta debilidad cuando seas fuerte, y fortaleza cuando seas débil.", by: "Sun Tzu, El arte de la guerra" },
    { text: "En la mente del principiante hay muchas posibilidades; en la del experto, pocas.", by: "Shunryu Suzuki, Mente zen, mente de principiante" },
    { text: "El camino del samurái se encuentra en la muerte.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "Tienes derecho a tus acciones, pero nunca a sus frutos.", by: "Bhagavad Gita 2.47" },
    { text: "Llévame de lo irreal a lo real.", by: "Brihadaranyaka Upanishad 1.3.28" },
    { text: "Si no soy para mí, ¿quién será para mí? Y si solo soy para mí, ¿qué soy?", by: "Hilel, Pirkei Avot 1:14" },
    { text: "No hay nada nuevo bajo el sol.", by: "Eclesiastés 1:9" },
    { text: "Estad quietos, y sabed.", by: "Salmo 46:11" },
    { text: "Todo fluye, nada permanece quieto.", by: "Heráclito" },
    { text: "Debéis esforzaros vosotros mismos; los Budas solo señalan el camino.", by: "Buda, Dhammapada 276" },
    { text: "Cada uno es su propio protector; ¿quién más podría serlo?", by: "Buda, Dhammapada 160" },
    { text: "Aunque venza mil veces a mil hombres en la batalla, es el mayor vencedor quien se vence a sí mismo.", by: "Buda, Dhammapada 103" },
    { text: "Evitar todo mal, cultivar el bien y purificar la mente: esta es la enseñanza de los Budas.", by: "Buda, Dhammapada 183" },
    { text: "Quien lo conoce no equivale a quien lo ama; quien lo ama no equivale a quien se deleita en ello.", by: "Confucio, Analectas 6.20" },
    { text: "¿Quién puede decir que la nueva generación no igualará a la presente?", by: "Confucio, Analectas 9.23" },
    { text: "El bien supremo es como el agua.", by: "Laozi, Tao Te King 8" },
    { text: "El mar es rey de los cien valles porque se sitúa por debajo de ellos.", by: "Laozi, Tao Te King 66" },
    { text: "Damos forma al barro para hacer una vasija, pero es su vacío lo que la hace útil.", by: "Laozi, Tao Te King 11" },
    { text: "Sin salir por tu puerta, puedes conocer los caminos del mundo.", by: "Laozi, Tao Te King 47" },
    { text: "Educar no es poner la vista en ojos ciegos; es volver el alma hacia la luz.", by: "Platón, La República 518c" },
    { text: "El fin de nuestra investigación no es el saber, sino la acción.", by: "Aristóteles, Ética a Nicómaco 1.3" },
    { text: "De la madera torcida de la humanidad nunca se hizo nada recto.", by: "Immanuel Kant, Idea de una historia universal" },
    { text: "Lo que no me mata me hace más fuerte.", by: "Friedrich Nietzsche, El crepúsculo de los ídolos" },
    { text: "Todos los males de la humanidad provienen de no saber quedarse tranquilo en una habitación, solo.", by: "Blaise Pascal, Pensamientos 139" },
    { text: "No te arrepientas de lo que has hecho.", by: "Miyamoto Musashi, El libro de los cinco anillos" },
    { text: "Considérate cada mañana como ya muerto.", by: "Yamamoto Tsunetomo, Hagakure" },
    { text: "La respuesta amable calma la ira.", by: "Proverbios 15:1" },
    { text: "No te dejes vencer por el mal; vence el mal con el bien.", by: "Romanos 12:21" },
    { text: "Todo tiene su tiempo.", by: "Eclesiastés 3:1" },
    { text: "Ciertamente, con la dificultad viene la facilidad.", by: "Corán 94:5-6" },
    { text: "Sé fiel a ti mismo.", by: "William Shakespeare, Hamlet 1.3" },
    { text: "Las dificultades fortalecen la mente, como el trabajo fortalece el cuerpo.", by: "Séneca, Cartas a Lucilio" },
    { text: "No eches a perder lo que tienes deseando lo que no tienes.", by: "Epicuro" },
    { text: "Es imposible vivir una vida agradable sin vivir con sabiduría, honradez y justicia.", by: "Epicuro, Máximas capitales 5" },
    { text: "De todo lo que la sabiduría ofrece para hacernos completamente felices, lo más grande es la amistad.", by: "Epicuro, Máximas capitales 27" },
    { text: "Cede, y serás preservado.", by: "Laozi, Tao Te King 22" },
    { text: "¿Quién puede esperar en calma a que el lodo se asiente? ¿Quién puede permanecer quieto hasta el momento de actuar?", by: "Laozi, Tao Te King 15" },
    { text: "El estratega victorioso solo busca la batalla cuando la victoria ya está asegurada.", by: "Sun Tzu, El arte de la guerra 4" },
    { text: "Mucho aprender no enseña a entender.", by: "Heráclito, fragmento 40" },
  ],
  zh: [
    { text: "学而不思则罔，思而不学则殆。", by: "孔子《论语》2.15" },
    { text: "己所不欲，勿施于人。", by: "孔子《论语》15.24" },
    { text: "恨不以恨止，唯以爱止。", by: "佛陀《法句经》5" },
    { text: "心为法本，心尊心使。", by: "佛陀《法句经》1" },
    { text: "使人烦恼的不是事物本身，而是人对事物的看法。", by: "爱比克泰德《手册》5" },
    { text: "人不能两次踏入同一条河流。", by: "赫拉克利特" },
    { text: "未经审视的人生不值得过。", by: "苏格拉底，柏拉图《申辩篇》" },
    { text: "千里之行，始于足下。", by: "老子《道德经》64" },
    { text: "知者不言，言者不知。", by: "老子《道德经》56" },
    { text: "认识你自己。", by: "德尔斐神庙铭文" },
    { text: "死亡与我们无关：我们存在时，死亡尚未来临；死亡来临时，我们已不复存在。", by: "伊壁鸠鲁《致墨诺寇的信》" },
    { text: "我们并非时间太少，而是浪费了太多。", by: "塞涅卡《论生命的短暂》" },
    { text: "人生很长，只要懂得如何利用。", by: "塞涅卡《论生命的短暂》" },
    { text: "我们拖延之时，生命已悄然流逝。", by: "塞涅卡《致卢西利乌斯书》" },
    { text: "立刻开始生活，把每一天当作一生来对待。", by: "塞涅卡《致卢西利乌斯书》101" },
    { text: "每一个新的开始，都源于另一个开始的结束。", by: "塞涅卡《致卢西利乌斯书》36" },
    { text: "我们在想象中受的苦，往往多于现实。", by: "塞涅卡《致卢西利乌斯书》13" },
    { text: "有时，活着本身就是一种勇气。", by: "塞涅卡《致卢西利乌斯书》24" },
    { text: "有些事情在我们掌控之中，有些则不然。", by: "爱比克泰德《手册》1" },
    { text: "不要希望事情按你的意愿发生，而要希望它们按其本来的样子发生，你的人生就会顺利。", by: "爱比克泰德《手册》8" },
    { text: "先问自己想成为什么样的人，然后去做你该做的事。", by: "爱比克泰德《论说集》" },
    { text: "不能自主者，就不是自由的人。", by: "爱比克泰德《论说集》" },
    { text: "报复的最好方式，就是不要变成伤害你的那个人。", by: "马可·奥勒留《沉思录》6.6" },
    { text: "不要再浪费时间争论好人应该是什么样子，去做一个好人吧。", by: "马可·奥勒留《沉思录》10.16" },
    { text: "行动的障碍反而推动行动。挡在路上的东西，本身就成了道路。", by: "马可·奥勒留《沉思录》5.20" },
    { text: "要过上幸福的生活，所需甚少。", by: "马可·奥勒留《沉思录》7.67" },
    { text: "向内看。善的源泉就在内心，它将永远涌流。", by: "马可·奥勒留《沉思录》7.59" },
    { text: "哲学始于惊奇。", by: "柏拉图《泰阿泰德篇》155d" },
    { text: "唯一真正的智慧，是知道自己一无所知。", by: "苏格拉底，源自柏拉图《申辩篇》21d" },
    { text: "开端是任何事业中最重要的部分。", by: "柏拉图《理想国》377a" },
    { text: "我们通过做正义的事情而变得正义，通过做节制的事情而变得节制。", by: "亚里士多德《尼各马可伦理学》2.1" },
    { text: "人天生是政治动物。", by: "亚里士多德《政治学》1.2" },
    { text: "要敢于求知！要有勇气运用你自己的理智。", by: "康德《什么是启蒙？》" },
    { text: "我知道什么？", by: "蒙田《随笔集》座右铭" },
    { text: "心有其理，而理性对此一无所知。", by: "帕斯卡尔《思想录》277" },
    { text: "一个人若有生存的理由，几乎能忍受任何生存的方式。", by: "尼采《偶像的黄昏》" },
    { text: "与怪物战斗的人，要当心自己不要在斗争中变成怪物。", by: "尼采《善恶的彼岸》IV.146" },
    { text: "在严冬之中，我发现自己心中有一个不可战胜的夏天。", by: "加缪《回到提帕萨》" },
    { text: "向上的路与向下的路，本是同一条。", by: "赫拉克利特，残篇60" },
    { text: "一个人的性格就是他的命运。", by: "赫拉克利特，残篇119" },
    { text: "学而时习之，不亦说乎？", by: "孔子《论语》1.1" },
    { text: "知之为知之，不知为不知，是知也。", by: "孔子《论语》2.17" },
    { text: "温故而知新，可以为师矣。", by: "孔子《论语》2.11" },
    { text: "见义不为，无勇也。", by: "孔子《论语》2.24" },
    { text: "智者不惑。", by: "孔子《论语》9.29" },
    { text: "君子不忧不惧。", by: "孔子《论语》12.4" },
    { text: "君子和而不同。", by: "孔子《论语》13.23" },
    { text: "德不孤，必有邻。", by: "孔子《论语》4.25" },
    { text: "性相近也，习相远也。", by: "孔子《论语》17.2" },
    { text: "诚者，天之道也。", by: "孔子《中庸》20" },
    { text: "如坚固的岩石不会被风暴撼动，智者也不会因赞誉或诽谤而动摇。", by: "佛陀《法句经》81" },
    { text: "一句能带来平安的话，胜过千句空洞的言辞。", by: "佛陀《法句经》100" },
    { text: "以不怒胜怒。", by: "佛陀《法句经》223" },
    { text: "胜利滋生仇恨，失败者活在痛苦之中。", by: "佛陀《法句经》201" },
    { text: "健康是最大的礼物，知足是最大的财富。", by: "佛陀《法句经》204" },
    { text: "心猿意马，难以驾驭，但可以修炼。", by: "佛陀《法句经》35" },
    { text: "不要去看别人的过错，看他们做了什么或没做什么。", by: "佛陀《法句经》50" },
    { text: "如花美而无香，美言若不践行，也是徒然。", by: "佛陀《法句经》51" },
    { text: "知人者智，自知者明。", by: "老子《道德经》33" },
    { text: "知足者富。", by: "老子《道德经》33" },
    { text: "天下之至柔，驰骋天下之至坚。", by: "老子《道德经》43" },
    { text: "圣人不积。既以为人，己愈有；既以与人，己愈多。", by: "老子《道德经》81" },
    { text: "善行者无辙迹；善言者无瑕谪。", by: "老子《道德经》27" },
    { text: "筌者所以在鱼，得鱼而忘筌。", by: "庄子《外物》，第26章" },
    { text: "至人之用心若镜，不将不迎，应而不藏。", by: "庄子《应帝王》，第7章" },
    { text: "凡事若无用，勿为之。", by: "宫本武藏《五轮书》" },
    { text: "以心观察，见那不可见之物。", by: "宫本武藏《五轮书》" },
    { text: "强而示之以弱，弱而示之以强。", by: "孙子《孙子兵法》" },
    { text: "初学者的心中有许多可能，专家的心中却只有少数。", by: "铃木俊隆《禅者的初心》" },
    { text: "武士之道，在于死。", by: "山本常朝《叶隐》" },
    { text: "你只有行动的权利，却没有行动成果的权利。", by: "《薄伽梵歌》2.47" },
    { text: "从虚妄引我到真实。", by: "《广林奥义书》1.3.28" },
    { text: "我不为自己，谁为我？我若只为自己，又是什么？", by: "希勒尔《格言书》1:14" },
    { text: "日光之下，并无新事。", by: "《传道书》1:9" },
    { text: "你们要安静，要知道。", by: "《诗篇》46:10" },
    { text: "万物流动，无物常住。", by: "赫拉克利特" },
    { text: "你们自己要努力，佛陀只是指明道路。", by: "佛陀《法句经》276" },
    { text: "人自己是自己的依靠，除了自己，还能依靠谁？", by: "佛陀《法句经》160" },
    { text: "即使在战场上战胜千万人，最伟大的胜利者仍是战胜自己的人。", by: "佛陀《法句经》103" },
    { text: "诸恶莫作，众善奉行，自净其意，是诸佛教。", by: "佛陀《法句经》183" },
    { text: "知之者不如好之者，好之者不如乐之者。", by: "孔子《论语》6.20" },
    { text: "后生可畏，焉知来者之不如今也？", by: "孔子《论语》9.23" },
    { text: "上善若水。", by: "老子《道德经》8" },
    { text: "江海之所以能为百谷王者，以其善下之。", by: "老子《道德经》66" },
    { text: "埏埴以为器，当其无，有器之用。", by: "老子《道德经》11" },
    { text: "不出户，知天下。", by: "老子《道德经》47" },
    { text: "教育不是把视力放进盲人的眼中，而是转向灵魂。", by: "柏拉图《理想国》518c" },
    { text: "我们探究的目的不是知识，而是行动。", by: "亚里士多德《尼各马可伦理学》1.3" },
    { text: "从人类弯曲的木材中，永远造不出笔直的东西。", by: "康德《世界公民观点下的普遍历史理念》" },
    { text: "那些不能杀死我的，会使我更强大。", by: "尼采《偶像的黄昏》" },
    { text: "人类所有的问题，都源于人无法安静地独自待在一个房间里。", by: "帕斯卡尔《思想录》139" },
    { text: "不要后悔你所做的事。", by: "宫本武藏《五轮书》" },
    { text: "每天早晨，都要把自己当作已经死去。", by: "山本常朝《叶隐》" },
    { text: "良言能消解怒气。", by: "《箴言》15:1" },
    { text: "不要被恶所胜，要以善胜恶。", by: "《罗马书》12:21" },
    { text: "凡事都有定期。", by: "《传道书》3:1" },
    { text: "苦难之后必有安乐。", by: "《古兰经》94:5-6" },
    { text: "忠于你自己。", by: "威廉·莎士比亚《哈姆雷特》1.3" },
    { text: "困难锻炼心灵，正如劳作锻炼身体。", by: "塞涅卡《致卢西利乌斯书》" },
    { text: "不要因渴望没有的东西，而毁掉你已经拥有的。", by: "伊壁鸠鲁" },
    { text: "不明智、不善良、不正义地生活，就不可能过上愉快的生活。", by: "伊壁鸠鲁《主要学说》5" },
    { text: "智慧所提供的一切，使人完全幸福的东西中，友谊是最伟大的。", by: "伊壁鸠鲁《主要学说》27" },
    { text: "委曲才能保全。", by: "老子《道德经》22" },
    { text: "谁能静以待浊水之清？谁能动以待时机之来？", by: "老子《道德经》15" },
    { text: "善战者，求之于势，不责于人。胜兵先胜而后求战。", by: "孙子《孙子兵法》4" },
    { text: "博学不等于懂得道理。", by: "赫拉克利特，残篇40" },
  ],
}

const engines = [
  { name: 'Kagi', url: 'https://kagi.com/search?q=', icon: `<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" fill-rule="evenodd" aria-hidden="true"><path d="M14.498 18.392h-5.14c-1.39 0-1.632-1.508-1.39-2.11.12-.302.423-.724.664-1.026a6.81 6.81 0 003.326.845 6.945 6.945 0 006.954-6.935c0-2.05-.907-3.86-2.298-5.186l.181-.181c.363-.362.907-.603 1.451-.543l.847.06V0h-1.451c-1.693 0-3.084 1.025-3.689 2.472a6.83 6.83 0 00-1.934-.301 6.945 6.945 0 00-6.954 6.935c0 1.507.484 2.954 1.33 4.1a1.84 1.84 0 01-.423.302l-.181.18c-1.391 1.327-2.056 3.015-1.693 4.945.181 1.025 1.088 2.11 1.995 2.714.605.422 1.39.603 2.177.603l5.804-.242c.665 0 1.27.302 1.633.905L16.432 24 20 22.794l-.605-1.327a5.425 5.425 0 00-4.897-3.075zm-2.48-12.543c1.814 0 3.326 1.508 3.326 3.317 0 1.809-1.512 3.316-3.325 3.316-1.814 0-3.326-1.507-3.326-3.316 0-1.87 1.451-3.317 3.325-3.317z"></path></svg>` },
  { name: 'Brave', url: 'https://search.brave.com/search?q=', icon: `<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" fill-rule="evenodd" aria-hidden="true"><path d="M17.544 2.375c.017-.005 1.844-.5 2.712.361.872.872 1.588 1.642 1.588 1.642l-.565 1.38v-.003.006-.003L22 7.8c-.014.05-2.112 7.983-2.357 8.954-.488 1.924-.819 2.663-2.202 3.638a212.634 212.634 0 01-4.305 2.917c-.41.252-.92.691-1.383.691-.463 0-.974-.439-1.383-.691a213.099 213.099 0 01-4.306-2.917c-1.383-.975-1.72-1.714-2.2-3.632-.246-.977-2.35-8.904-2.364-8.96l.722-2.045-.566-1.383s.722-.764 1.594-1.63c.866-.872 2.712-.36 2.712-.36L8.066 0h7.373l2.105 2.375zm-5.797 12.557c-.138 0-1.04.318-1.762.691l-.457.234c-.487.253-.823.428-.956.506-.168.108-.066.306.09.414.15.103 2.195 1.684 2.394 1.865l.09.078c.186.168.432.391.607.391.174 0 .415-.223.607-.391l.084-.078c.2-.169 2.244-1.756 2.394-1.865.15-.108.258-.3.09-.408-.133-.084-.475-.253-.956-.506h-.006l-.457-.24c-.722-.373-1.623-.691-1.762-.691zm.006-11.276c-.35.02-.694.092-1.023.211l-.378.126c-.493.169-.969.331-1.21.331-.312 0-2.554-.428-2.584-.433 0 0-2.706 3.26-2.706 3.957 0 .577.228.805.504 1.07l.174.175 2.033 2.152.06.067c.204.204.5.498.29.998l-.043.102c-.228.535-.511 1.203-.15 1.876.384.716 1.046 1.19 1.467 1.118.42-.084 1.419-.601 1.78-.841.367-.229 1.52-1.19 1.521-1.551 0-.307-.829-.812-1.238-1.053l-.18-.12-.199-.12c-.367-.229-1.035-.644-1.047-.825-.018-.228-.017-.294.283-.853l.21-.379c.289-.487.602-1.029.536-1.426-.085-.433-.777-.685-1.36-.901l-.21-.078-.613-.229c-.583-.222-1.232-.463-1.34-.511-.145-.073-.11-.132.335-.174l.223-.025c.553-.06 1.582-.168 2.08-.03l.32.09c.564.145 1.25.337 1.316.445l.03.048c.067.09.109.145.037.53l-.121.607c-.15.806-.391 2.069-.421 2.351l-.012.115c-.042.312-.066.529.301.613.438.119.884.206 1.335.259.216 0 .824-.144 1.24-.24l.095-.025c.367-.078.343-.289.3-.602l-.011-.12c-.03-.282-.27-1.54-.42-2.345l-.122-.614c-.072-.384-.024-.439.036-.529l.03-.048c.067-.108.753-.294 1.318-.444l.318-.091c.5-.138 1.528-.03 2.081.03l.216.018c.451.048.493.108.343.18-.11.049-.758.29-1.341.512-.273.108-.547.21-.823.307-.583.216-1.275.468-1.36.907-.066.391.247.939.535 1.42l.21.379c.301.56.308.625.284.854-.012.18-.68.595-1.053.824l-.192.126-.181.108c-.41.247-1.238.758-1.238 1.059 0 .367 1.16 1.316 1.521 1.55.367.235 1.36.758 1.78.836.421.078 1.082-.396 1.467-1.112.36-.673.078-1.335-.15-1.876l-.042-.102c-.21-.5.084-.794.289-1.004l.065-.06 2.02-2.147.181-.181c.271-.265.505-.493.505-1.07 0-.698-2.706-3.957-2.706-3.957-.03.006-2.275.44-2.586.44l.007-.007c-.252 0-.722-.156-1.215-.337l-.379-.12c-.612-.21-1.02-.21-1.022-.21z"></path></svg>` },
  { name: 'Google', url: 'https://www.google.com/search?q=', icon: `<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" fill-rule="evenodd" aria-hidden="true"><path d="M23 12.245c0-.905-.075-1.565-.236-2.25h-10.54v4.083h6.186c-.124 1.014-.797 2.542-2.294 3.569l-.021.136 3.332 2.53.23.022C21.779 18.417 23 15.593 23 12.245z"></path><path d="M12.225 23c3.03 0 5.574-.978 7.433-2.665l-3.542-2.688c-.948.648-2.22 1.1-3.891 1.1a6.745 6.745 0 01-6.386-4.572l-.132.011-3.465 2.628-.045.124C4.043 20.531 7.835 23 12.225 23z"></path><path d="M5.84 14.175A6.65 6.65 0 015.463 12c0-.758.138-1.491.361-2.175l-.006-.147-3.508-2.67-.115.054A10.831 10.831 0 001 12c0 1.772.436 3.447 1.197 4.938l3.642-2.763z"></path><path d="M12.225 5.253c2.108 0 3.529.892 4.34 1.638l3.167-3.031C17.787 2.088 15.255 1 12.225 1 7.834 1 4.043 3.469 2.197 7.062l3.63 2.763a6.77 6.77 0 016.398-4.572z"></path></svg>` },
  { name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=', icon: `<svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 0C5.37 0 0 5.37 0 12s5.37 12 12 12 12-5.37 12-12S18.63 0 12 0zm0 .984C18.083.984 23.016 5.916 23.016 12S18.084 23.016 12 23.016.984 18.084.984 12C.984 5.917 5.916.984 12 .984zm0 .938C6.434 1.922 1.922 6.434 1.922 12c0 4.437 2.867 8.205 6.85 9.55-.237-.82-.776-2.753-1.6-6.052-1.184-4.741-2.064-8.606 2.379-9.813.047-.011.064-.064.03-.093-.514-.467-1.382-.548-2.233-.38a.06.06 0 0 1-.07-.058c0-.011 0-.023.011-.035.205-.286.572-.507.822-.64a1.843 1.843 0 0 0-.607-.335c-.059-.022-.059-.12-.006-.144.006-.006.012-.012.024-.012 1.749-.233 3.586.292 4.49 1.448.011.011.023.017.035.023 2.968.635 3.509 4.837 3.328 5.998a9.607 9.607 0 0 0 2.346-.576c.746-.286 1.008-.222 1.101-.053.1.193-.018.513-.28.81-.496.567-1.393 1.01-2.974 1.137-.546.044-1.029.024-1.445.006-.789-.035-1.339-.059-1.633.39-.192.298-.041.998 1.487 1.22 1.09.157 2.078.047 2.798-.034.643-.07 1.073-.118 1.172.069.21.402-.996 1.207-3.066 1.224-.158 0-.315-.006-.467-.011-1.283-.065-2.227-.414-2.816-.735a.094.094 0 0 1-.035-.017c-.105-.059-.31.045-.188.267.07.134.444.478 1.004.776-.058.466.087 1.184.338 2l.088-.016c.041-.009.087-.019.134-.025.507-.082.775.012.926.175.717-.536 1.913-1.294 2.03-1.154.583.694.66 2.332.53 2.99-.004.012-.017.024-.04.035-.274.117-1.783-.296-1.783-.511-.059-1.075-.26-1.173-.493-1.225h-.156c.006.006.012.018.018.03l.052.12c.093.257.24 1.063.13 1.26-.112.199-.835.297-1.284.303-.443.006-.543-.158-.637-.408-.07-.204-.103-.675-.103-.95a.857.857 0 0 1 .012-.216c-.134.058-.333.193-.397.281-.017.262-.017.682.123 1.149.07.221-1.518 1.164-1.74.99-.227-.181-.634-1.952-.459-2.67-.187.017-.338.075-.42.191-.367.508.093 2.933.582 3.248.257.169 1.54-.553 2.176-1.095.105.145.305.158.553.158.326-.012.782-.06 1.103-.158.192.45.423.972.613 1.388 4.47-1.032 7.803-5.037 7.803-9.82 0-5.566-4.512-10.078-10.078-10.078zm1.791 5.646c-.42 0-.678.146-.795.332-.023.047.047.094.094.07.14-.075.357-.161.701-.156.328.006.516.09.67.159l.023.01c.041.017.088-.03.059-.065-.134-.18-.332-.35-.752-.35zm-5.078.198a1.24 1.24 0 0 0-.522.082c-.454.169-.67.526-.67.76 0 .051.112.057.141.011.081-.123.21-.31.617-.478.408-.17.73-.146.951-.094.047.012.083-.041.041-.07a.989.989 0 0 0-.558-.211zm5.434 1.423a.651.651 0 0 0-.655.647.652.652 0 0 0 1.307 0 .646.646 0 0 0-.652-.647zm.283.262h.008a.17.17 0 0 1 .17.17c0 .093-.077.17-.17.17a.17.17 0 0 1-.17-.17c0-.09.072-.165.162-.17zm-5.358.076a.752.752 0 0 0-.758.758c0 .42.338.758.758.758s.758-.337.758-.758a.756.756 0 0 0-.758-.758zm.328.303h.01c.112 0 .2.089.2.2 0 .11-.088.197-.2.197a.195.195 0 0 1-.197-.198c0-.107.082-.194.187-.199z"/></svg>` }
]

// DuckDuckGo is the default until the visitor picks another engine.
let engine = engines.findIndex((e) => e.name === 'DuckDuckGo')
try {
  const saved = engines.findIndex((e) => e.name === localStorage.getItem('engine'))
  if (saved >= 0) engine = saved
} catch {}

const showEngine = () => {
  engineButton.innerHTML = engines[engine].icon
  engineButton.title = `Search engine: ${engines[engine].name}. Click to change.`
  engineButton.setAttribute('aria-label', engineButton.title)
}
showEngine()

engineButton.addEventListener('click', () => {
  engine = (engine + 1) % engines.length
  showEngine()
  try { localStorage.setItem('engine', engines[engine].name) } catch {}
  searchBox.focus()
})

// Enter submits the form; preventDefault keeps the page from reloading.
// An empty submit gets a short hint in the field instead of doing nothing.
let hintTimer
searchForm.addEventListener('submit', (e) => {
  e.preventDefault()
  const value = searchBox.value.trim()
  if (value.length > 0) {
    location.href = engines[engine].url + encodeURIComponent(value)
    return
  }
  searchBox.value = ''
  searchBox.placeholder = 'Type something to search'
  searchBox.focus()
  clearTimeout(hintTimer)
  hintTimer = setTimeout(() => { searchBox.placeholder = '' }, 1500)
})

const updateClock = () => {
  const now = new Date()
  const time = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
  const date = now.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })
  clockTime.textContent = time
  clockTime.dateTime = now.toISOString()
  clockDate.textContent = date
}
updateClock()
setInterval(updateClock, 30000)

// A new quote every six hours, so the same one stays put for that window.
const quoteText = document.getElementById('quote-text')
const quoteBy = document.getElementById('quote-by')
const quoteLang = (navigator.language || 'en').slice(0, 2).toLowerCase()
const translated = quotes[quoteLang] || []
const quoteList = quotes.en.map((q, i) => translated[i] || q)
// Clicking the quote steps to the next one; the six-hour rotation keeps going from there.
let quoteOffset = 0
const showQuote = () => {
  const sixHours = Math.floor(Date.now() / (6 * 3600 * 1000))
  const current = quoteList[(sixHours + quoteOffset) % quoteList.length]
  quoteText.textContent = `“${current.text}”`
  quoteBy.textContent = current.by
}
showQuote()
setInterval(showQuote, 60000)
document.getElementById('quote').addEventListener('click', () => {
  quoteOffset += 1
  showQuote()
})

const showTheme = () => {
  const stored = root.dataset.theme || 'auto'
  modeButtons.forEach((button) => {
    button.setAttribute('aria-pressed', String(button.dataset.themeValue === stored))
  })
}

modeButtons.forEach((button) => {
  button.addEventListener('click', () => {
    const value = button.dataset.themeValue
    if (value === 'auto') {
      delete root.dataset.theme
      try { localStorage.removeItem('theme') } catch {}
    } else {
      root.dataset.theme = value
      try { localStorage.setItem('theme', value) } catch {}
    }
    showTheme()
  })
})
showTheme()

window.onload = () => {
  document.getElementsByTagName('body')[0].removeAttribute('class')
}
